thematters/matters-web

- src/components/ClientUpdater/index.tsx
- src/views/ArticleDetail/gql.ts
> feat(component): change logic of new user default feed

- src/common/gql/fragmentTypes.json
- src/components/Notice/TagAddEditorNotice.tsx
- src/components/Notice/TagAdoptionNotice.tsx
- src/components/Notice/TagLeaveEditorNotice.tsx
- src/components/Notice/TagLeaveNotice.tsx
- src/components/Notice/index.tsx
> feat(notice): add tag management notices

- src/components/GQL/mutations/updateTagSetting.ts
- src/components/Notice/ArticleTagHasBeenAddedNotice.tsx
- src/components/Notice/ArticleTagHasBeenRemovedNotice.tsx
- src/components/Notice/ArticleTagHasBeenUnselectedNotice.tsx
- src/components/Notice/TagAddEditorNotice.tsx
- src/components/Notice/TagAdoptionNotice.tsx
- src/components/Notice/TagLeaveEditorNotice.tsx
> feat(notice): add notice descriptions for tag management actions

- src/views/TagDetail/Articles/index.tsx
> fix(component): fix tag feeds are not refreshing after adding articles

- src/components/Dialogs/TagEditorDialog/List/index.tsx
- src/components/Dialogs/TagEditorDialog/Remove/index.tsx
- src/components/Dialogs/TagEditorDialog/Remove/styles.css
- src/components/Dialogs/TagEditorDialog/SearchSelect/index.tsx
- src/components/Dialogs/TagEditorDialog/index.tsx
> fix(component): add display name in tag editor remove dialog

- package-lock.json
- package.json
- src/common/styles/utils/content.article.css
- src/components/Editor/Article/styles.css
- src/views/Me/DraftDetail/index.tsx
> fix(editor): fix editor horizontal overflow on figure (image, iframe, etc.)

- src/views/User/Tags/UserTags.tsx
> feat(tag): revise description in user's tag feed due to now listing tags owned and maintained

- src/common/styles/vendors/quill.bubble.css
- src/components/Editor/Article/styles.css
- src/components/Layout/Header/styles.css
- src/components/Layout/index.tsx
- src/views/Me/DraftDetail/index.tsx
* Fix the wrong position of placehoder;
* Using `height` instead of `max-height` to increase default editor height for larger clickable hot area;
* Fix extra container scrollbar by hiding `Layout > aside` on mobile;
> Fix Editor UI

- src/common/styles/utils/content.article.css
- src/components/Editor/Article/styles.css
- src/views/Me/DraftDetail/index.tsx
Previous bugfix #1567 broke the behavior of the editor toolbar, it won't appear when we focus on newline.
> fix(editor): revert #1567 and make figure non-full width

- src/components/Editor/BottomBar/styles.css
- src/views/ArticleDetail/EditMode/index.tsx
- src/views/Me/DraftDetail/index.tsx
> fix(component): change breakpoints for editor bottom bar

- src/views/Guide/content.ts
- src/views/Home/Feed/SortBy/index.tsx
- src/views/Home/Feed/gql.ts
- src/views/Home/Feed/index.tsx
also, update links in guide page;
> feat(feed): remove homepage topics feed; 

- src/common/enums/events.ts
- src/components/Dialogs/RecommendAuthorDialog/index.tsx
- src/components/Dialogs/RecommendTagDialog/index.tsx
- src/components/OnboardingTasks/Dialog/index.tsx
- src/components/OnboardingTasks/NavBar/index.tsx
- src/components/OnboardingTasks/Tasks/index.tsx
- src/components/OnboardingTasks/Widget/index.tsx
* fix dialogs are closed unexpectedly; 
* hide 「編輯精選」feed of `<RecommendTagsDialog>`;
* revise texts;
> Fix Onboarding Tasks

- package-lock.json
- package.json
- src/components/Forms/PaymentForm/PayTo/Confirm/index.tsx
`formik@2.2.x` causes donation input validation incorrectly.
> fix(form): rollback formik to 2.1.x

- src/components/Notice/ArticleArticleNotice/ArticleNewCollectedNotice.tsx
- src/components/Notice/ArticleNotice/ArticleNewAppreciationNotice.tsx
- src/components/Notice/ArticleNotice/ArticleNewSubscriberNotice.tsx
- src/components/Notice/ArticleTagNotice/ArticleTagAddedNotice.tsx
- src/components/Notice/ArticleTagNotice/ArticleTagRemovedNotice.tsx
- src/components/Notice/ArticleTagNotice/ArticleTagUnselectedNotice.tsx
- src/components/Notice/CommentCommentNotice/CommentNewReplyNotice.tsx
- src/components/Notice/CommentNotice/ArticleNewCommentNotice.tsx
- src/components/Notice/CommentNotice/CommentPinnedNotice.tsx
- src/components/Notice/CommentNotice/SubscribedArticleNewCommentNotice.tsx
- src/components/Notice/TagNotice/TagAddEditorNotice.tsx
- src/components/Notice/TagNotice/TagAdoptionNotice.tsx
- src/components/Notice/TagNotice/TagLeaveEditorNotice.tsx
- src/components/Notice/TagNotice/TagLeaveNotice.tsx
- src/components/Notice/UserNotice/UserNewFollowerNotice.tsx
https://github.com/thematters/matters-server/pull/1665
> fix(notice): remove unused `key` of CommentPinnedNotice

- src/components/Notice/ArticleNotice/ArticleNewAppreciationNotice.tsx
- src/components/Notice/ArticleNotice/ArticleNewSubscriberNotice.tsx
- src/components/Notice/CommentCommentNotice/CommentNewReplyNotice.tsx
- src/components/Notice/CommentNotice/ArticleNewCommentNotice.tsx
- src/components/Notice/CommentNotice/SubscribedArticleNewCommentNotice.tsx
- src/components/Notice/NoticeTypeIcon.tsx
> [hotfix - master] fix(icon): fix notice icons

- src/common/styles/mixins/mixins.css
- src/components/Dialog/Footer/styles.css
- src/components/Layout/NavBar/styles.css
- src/components/Layout/SideFooter/styles.css
- src/components/Layout/styles.css
- src/components/OnboardingTasks/NavBar/index.tsx
- src/components/OnboardingTasks/NavBar/styles.css
- src/views/ArticleDetail/Toolbar/index.tsx
- src/views/ArticleDetail/Toolbar/styles.css
- src/views/ArticleDetail/Wall/styles.css
* Fix collapsed safe-area of bottom bars by adding `safe-area-botttom` mixin;
---
> [hotfix - master] fix(style): fix safe area of bottom bars

- src/pages/[name]/index.tsx
- src/views/Circle/Detail/Profile/AuthorWidget/gql.ts
- src/views/Circle/Detail/Profile/AuthorWidget/index.tsx
- src/views/Circle/Detail/Profile/AuthorWidget/styles.css
- src/views/Circle/Detail/Profile/gql.ts
- src/views/Circle/Detail/Profile/index.tsx
- src/views/Circle/Detail/Profile/styles.css
> feat(circle): showing author in circle detail

- src/components/Dialogs/PaymentPointerDialog/Explainer/index.tsx
- src/components/Dialogs/PaymentPointerDialog/Explainer/styles.css
- src/components/Dialogs/PaymentPointerDialog/SetPaymentPointerForm.tsx
> feat(payment pointer): add explainer to payment pointer

- src/common/utils/withApollo.ts
> fix(withapollo): pass request header to apollo init

- src/views/ArticleDetail/Wall/Circle/styles.css
- src/views/ArticleDetail/index.tsx
- src/views/ArticleDetail/styles.css
- src/views/Circle/Broadcast/index.tsx
- src/views/Circle/Discussion/index.tsx
- src/views/Circle/Works/gql.ts
- src/views/Circle/Works/index.tsx
- src/views/TagDetail/Articles/index.tsx
- src/views/TagDetail/Community/Participants/index.tsx
* Fix missing subscription banner causes by [typos](https://github.com/thematters/matters-web/pull/1850/files#diff-cddef2804953a4a69352d3c8d6de42b235d0048e30b52be019b807e7efd778cdR205);
* Fix [pagination](https://github.com/thematters/matters-web/pull/1850/files#diff-136d7d4f31b4eaf9e07033f597ffcfa9c06502fbb7336b3d779054e5c3cb964fR49) of circle works ;
* Hide upvote/downvote on broadcast;
* Fix space collapsing of circle wall;
> Fix Circle Detail

- .github/workflows/deploy.yml
- .github/workflows/storybook.yml
- .github/workflows/test.yml
* prevent triggering `deploy.yml` workflow on pull request;
* trigger `storybook.yml` only if the pull request was labeled with `storybook` [1];
[1] Relabel is needed if the PR has more commits;
> ci: prevent deployment on pull request

- src/components/Dialogs/PaymentPointerDialog/index.tsx
- src/components/Head/index.tsx
- src/views/ArticleDetail/gql.ts
- src/views/ArticleDetail/index.tsx
> fix(payment pointer): add payment pointer meta tag to head

- src/common/styles/utils/content.article.css
- src/components/ArticleDigest/DropdownActions/AddCircleArticle/Button.tsx
- src/components/ArticleDigest/DropdownActions/AddCircleArticle/Dialog.tsx
- src/components/ArticleDigest/DropdownActions/AddCircleArticle/index.tsx
- src/components/ArticleDigest/DropdownActions/index.tsx
- src/components/CircleDigest/Price/index.tsx
- src/components/Dialogs/AppreciatorsDialog/index.tsx
- src/components/Dialogs/DonatorsDialog/index.tsx
- src/components/Dialogs/FingerprintDialog/index.tsx
- src/components/SearchSelect/StagingArea/index.tsx
- src/components/UserProfile/DropdownActions/EditProfileDialog/index.tsx
- src/components/UserProfile/DropdownActions/index.tsx
- src/components/UserProfile/FollowersDialog/index.tsx
- src/components/UserProfile/FollowingDialog/index.tsx
- src/stories/mocks/index.ts
- src/views/ArticleDetail/CustomizedSummary/index.tsx
- src/views/ArticleDetail/CustomizedSummary/styles.css
- src/views/Circle/Profile/AddCircleArticle/Dialog/index.tsx
- src/views/Circle/Profile/DropdownActions/index.tsx
- src/views/Circle/Profile/FollowersDialog/index.tsx
- src/views/Me/DraftDetail/index.tsx
- src/views/TagDetail/DropdownActions/index.tsx
* supports add article to circle via dropdown actions;
* show toast with login button on unauthed viewer click circle price button;
* fix article summary style;
> Circle Enhancement

- src/views/About/Footer/index.tsx
- src/views/About/Hero/index.tsx
- src/views/About/Intro/index.tsx
- src/views/About/JoinUs/index.tsx
- src/views/About/Stats/index.tsx
- src/views/About/Team/index.tsx
- src/views/About/Timeline/index.tsx
> feat(about us page): add english text to about us page

- src/views/ArticleDetail/index.tsx
> fix(translation button): fix client language detection for translation button

- src/views/ArticleDetail/index.tsx
> *[master]* hoxfix(translate button): fix client language detection of translate button

- public/static/manifest.json
- src/components/Editor/BottomBar/MoreActions/Dialog.tsx
- src/components/Head/index.tsx
- src/views/ArticleDetail/EditMode/index.tsx
Also,
* Revise fallback `og:description`;
> fix(circle): fix missing save button on circle management dialog

- src/common/styles/layouts.css
- src/views/About/Footer/styles.css
- src/views/About/Hero/styles.css
- src/views/Me/Wallet/Buttons/styles.css
The behavior of CSS Grid on Firefox may break the layout when the content width overflow.
ref: https://stackoverflow.com/questions/43311943/prevent-content-from-expanding-grid-items
> fix(style): fix CSS Grid blowout

- src/components/Editor/SettingsDialog/List/ListItem/styles.css
- src/components/Editor/Sidebar/Management/index.tsx
- src/components/Editor/ToggleAccess/SelectLicense/index.tsx
- src/components/Editor/ToggleAccess/index.tsx
- src/components/Editor/ToggleAccess/styles.css
- src/components/Form/Select/Option/index.tsx
- src/components/Form/Select/Option/styles.css
- src/components/Form/Select/index.tsx
- src/views/Me/DraftDetail/hooks.ts
* improve `<ToggleAccess>` UI;
* fix license can't be changed on draft editor
> Fix license setting

- src/components/Analytics/PageViewTracker/index.tsx
- src/components/ClientUpdater/index.tsx
- src/components/Form/DropdownInput/index.tsx
- src/components/GlobalDialogs/TermAlertDialog/index.tsx
- src/components/Layout/Header/BackButton/index.tsx
- src/components/ProgressBar/index.tsx
- src/views/ArticleDetail/index.tsx
- src/views/Me/DraftDetail/PublishState/PublishedState.tsx
- src/views/Me/Drafts/index.tsx
- src/views/Search/index.tsx
**Before**
Redirect back to the draft detail page;
**Current**
Redirect back to the previous page of draft detail page;
> fix(router): fix back button behavior after publishing draft

- package.json
- src/components/Charts/StackedAreaChart/Area.tsx
- src/stories/components/Charts/Charts.tsx
- src/views/Circle/Analytics/FollowerAnalytics/index.tsx
- src/views/Circle/Analytics/IncomeAnalytics/gql.ts
- src/views/Circle/Analytics/IncomeAnalytics/index.tsx
- src/views/Circle/Analytics/InfoTiles/index.tsx
- src/views/Circle/Analytics/InfoTiles/styles.css
- src/views/Circle/Analytics/SubscriberAnalytics/index.tsx
- src/views/Circle/Analytics/SubscriberAnalytics/styles.global.css
* rename income fields;
* add color indicator to tooltip and info tiles;
> Enhance circle analytics

- src/components/Head/index.tsx
- src/views/ArticleDetail/index.tsx
- src/views/User/Articles/UserArticles.tsx
- src/views/User/Articles/gql.ts
this is so far adding Json-LD to articles page (`/@userName/...-mediaHash`) only
> feat/seo-json-ld: enhance articles SEO with Json-LD data

- src/components/Avatar/index.tsx
- src/components/Context/Viewer/index.tsx
the server doesn't handle such a high rate of calling right now;
but leave the badge showing on UserProfile page and ChangAvatar page should still work fine
> comment out checking nfts on user avatar

- src/components/Dialogs/ShareDialog/index.tsx
> try share decoded link

- src/components/Editor/ToggleAccess/SelectLicense/index.tsx
> open ARR license to all users

- src/components/Editor/ToggleAccess/index.tsx
- src/views/Me/DraftDetail/hooks.ts
allow arr license open to public
resolves #2335 [Web] - Support ARR license for article 5 pt feature request
> change paywall access to only when in circle and license type arr

- package-lock.json
- package.json
```diff
-        "@matters/matters-editor": "^0.1.24",
+        "@matters/matters-editor": "^0.1.26",
```
> bump "matters-editor" to "^0.1.26"

- src/components/Forms/WalletAuthForm/Connect.tsx
- src/views/Me/Settings/ConnectWallet/index.tsx
* refresh page after wallet connection;
> feat(wallet): hide ToS checkbox for wallet login

- src/common/utils/text.ts
- src/components/Dialogs/TagDialog/Content.tsx
> fix(tag): use stripPunctPrefixSuffix in create-tag form

- src/common/utils/text.ts
- src/components/Dialogs/ShareDialog/Content.tsx
- src/components/Dialogs/ShareDialog/index.tsx
- src/components/Head/index.tsx
- src/components/Layout/Header/ShareButton/index.tsx
- src/components/Share/Buttons/Twitter.tsx
- src/components/UserProfile/index.tsx
- src/views/ArticleDetail/EditMode/PublishState/gql.ts
- src/views/ArticleDetail/Toolbar/index.tsx
- src/views/ArticleDetail/index.tsx
- src/views/Circle/Profile/gql.ts
- src/views/Circle/Profile/index.tsx
- src/views/TagDetail/index.tsx
- src/views/User/Articles/UserArticles.tsx
- src/views/User/Comments/UserComments.tsx
- src/views/User/Subscriptions/UserSubscriptions.tsx
- src/views/User/Tags/UserTags.tsx
> feat/twitter-card-large: [Web] - twitter:card summary_large_image

- src/common/utils/analytics.ts
- src/components/Dialogs/index.tsx
- src/components/Editor/Sidebar/Tags/index.tsx
- src/components/Tag/index.tsx
- src/components/Tag/styles.css
- src/views/ArticleDetail/EditMode/index.tsx
- src/views/Me/DraftDetail/Sidebar/index.tsx
> feat(remove-tag-button): add clear button to each staged tag

- src/components/Head/index.tsx
- src/pages/_document.tsx
- src/views/Circle/Profile/index.tsx
also fixed some errors/warnings from https://validator.w3.org/nu/?doc=https://matters.news
> fix(meta-headers): fixed typo in circle profile page meta headers

- src/common/utils/analytics.ts
- src/components/Dialogs/ShareDialog/index.tsx
to compare with the number of events which indeed clicked share a social channel
> feat(share_dialog): track event of open share dialog

- src/components/Tag/index.tsx
- src/components/TextIcon/index.tsx
- src/components/TextIcon/styles.css
to be able select(&copy) text from existing tags, and paste into new article publishing
> feat(allow-user-select): allowUserSelect for tag text-icon

- src/components/GQL/queries/tagArticles.ts
- src/views/Home/Feed/gql.ts
- src/views/Tags/index.tsx
- src/views/User/Articles/gql.ts
> fix: increase query fetch size for articles and tags

- package-lock.json
- package.json
- src/common/utils/analytics.ts
- src/components/Analytics/TagExposureTracker/index.tsx
- src/components/Analytics/index.ts
- src/views/ArticleDetail/TagList/index.tsx
> hotrelease/4.3.3: tag_exposure tracking

- package.json
- src/common/utils/datetime/absolute.ts
- src/components/Comment/FooterActions/DownvoteButton/index.tsx
- src/components/Dialogs/FingerprintDialog/Content.tsx
- src/components/Dialogs/FingerprintDialog/index.tsx
- src/views/ArticleDetail/MetaInfo/index.tsx
- src/views/Follow/Feed/UserPublishArticleActivity/index.tsx
Release/4.3.5 #2571 
- revising edit iscn
- use date format of `May 22nd, 2022`
- hide revisedAt timestamp, only show edited or not
- skip wording of 'published at'
- feat(hide-downvote): keep all downvote functionality without showing numbers
> merge back master from already Release/4.3.5 #2571

- src/components/UserProfile/DropdownActions/EditProfileDialog/Content.tsx
fix can't edit user profile error
> hotfix: editor-profile-error

- src/components/Dialogs/SearchSelectDialog/index.tsx
- src/components/Editor/Sidebar/Tags/index.tsx
- src/components/Editor/TagCustomStagingArea/gql.ts
- src/components/Editor/TagCustomStagingArea/index.tsx
Also change tag `<SearchSelectDialog>` to smaller width.
> feat(tag): remove recommended tags from tag selector

- src/components/GQL/queries/searchTags.ts
- src/components/SearchSelect/SearchSelectNode/index.tsx
- src/components/SearchSelect/SearchingArea/index.tsx
- src/components/Tag/index.tsx
- src/components/TagDigest/Feed/index.tsx
- src/components/TagDigest/Sidebar/index.tsx
- src/stories/mocks/index.ts
related issue https://github.com/thematters/matters-server/pull/2632
> feat(tag): sync with server changes on `TagSearchResult` type

- package-lock.json
- package.json
**related attempts:**
* https://github.com/thematters/matters-web/pull/2609
* https://github.com/thematters/matters-web/pull/2606
> fix(ssr): bump next.js to 12.2.3

- src/views/Home/Announcements/Carousel/index.tsx
- src/views/Home/Announcements/Carousel/styles.css
https://github.com/thematters/serverless-file-post-processing/issues/616
https://github.com/thematters/serverless-file-post-processing/issues/609
> feat: use responsive image for annoncement cover

- src/common/utils/url.ts
**Related Issues**
* https://github.com/thematters/serverless-file-post-processing/issues/609
* https://github.com/thematters/serverless-file-post-processing/issues/616
> feat(image): enable responsive image for gif

- src/components/Comment/Feed/index.tsx
- src/components/Comment/FooterActions/DownvoteButton/index.tsx
- src/components/Comment/FooterActions/UpvoteButton/index.tsx
- src/components/Comment/FooterActions/index.tsx
- src/components/Tag/index.tsx
Reverts thematters/matters-web#2621
> Revert "feat(downvote): remove query field of downvote counts"

- src/common/utils/withApollo.ts
Reverts thematters/matters-web#2650
> Revert "[hotfix - prod] fix(api): turn off rejectUnauthorized and make `Host` header explicitly"

- src/common/utils/withApollo.ts
Reverts thematters/matters-web#2654
> Revert "revert #2650"

- src/views/Home/Announcements/Carousel/styles.css
Reverts thematters/matters-web#2666
> Revert "[hotfix] fix(announcement-cover): incorrect z-index"

- src/common/enums/index.ts
- src/common/utils/text.ts
- src/components/Dialogs/TagDialog/Content.tsx
- src/components/SearchSelect/SearchingArea/index.tsx
- src/components/Share/Buttons/Twitter.tsx
- src/views/ArticleDetail/Toolbar/index.tsx
- src/views/ArticleDetail/index.tsx
- src/views/TagDetail/index.tsx
applied same changes as in thematters/matters-server#2605
resolve thematters/matters-web#2507
> feat(tag-names): regex pattern for creating new tags #2507

- src/common/utils/analytics.ts
- src/components/GQL/queries/tagArticles.ts
- src/views/TagDetail/Articles/index.tsx
- src/views/TagDetail/Community/Maintainers/index.tsx
- src/views/TagDetail/Community/Participants/index.tsx
- src/views/TagDetail/index.tsx
- src/views/TagDetail/styles.css
Base branch is `feat/tag-detail-tabs` (https://github.com/thematters/matters-web/pull/2680)
> feat(tag-detail): add hottest feed to tag detail page

- package.json
- src/views/TagDetail/RelatedTags/index.tsx
- fix with the function call, from previous problem was a meta function not calling
- and, avoid the confusing onClick meta function naming
> fix(relate-tags): send with trackRelatedTags instead

- src/components/ArticleDigest/Title/index.tsx
- src/components/ArticleDigest/Title/styles.css
https://github.com/thematters/matters-web/issues/2626
> feat:truncate title in article card.

- src/components/Tag/index.tsx
- src/components/Tag/styles.css
- src/components/TagDigest/Sidebar/index.tsx
- src/components/UserDigest/Rich/index.tsx
- src/components/UserDigest/Rich/styles.css
- src/views/Home/Feed/Authors/index.tsx
- src/views/Home/Sidebar/Authors/index.tsx
- src/views/TagDetail/RelatedTags/index.tsx
add props in `<Tag>` & `<UserDigest.Rich>`
> fix: name length limit

- src/components/Notice/CircleNotice/CircleNewBroadcastComments.tsx
- src/components/Notice/CircleNotice/CircleNewDiscussionComments.tsx
https://paper.dropbox.com/doc/Matters--BnjnQFugWwVDWzYJUwpsDpZiAg-jWhP7c3QBJKT4RT73xLab
> feat(notice): revise circle notice copies

- src/common/enums/index.ts
- src/common/utils/text.ts
- src/components/Analytics/PageViewTracker/index.tsx
- src/components/Dialogs/TagDialog/Content.tsx
- src/components/Dialogs/TagDialog/styles.css
- src/components/Form/DropdownInput/index.tsx
- change length limit to 50; instead of 40;
- squeeze all spaces except the first;
> fix(tags-hint): tag creation hint

- src/common/utils/analytics.ts
- src/components/Analytics/CardExposureTracker/index.tsx
- src/components/Analytics/PageViewTracker/index.tsx
- src/components/Analytics/TagExposureTracker/index.tsx
* ae98cedb3 feat(track-exp): add delay_msecs to track delays of exposure events
* 0d05ec180 fix(page-referrer): should be a full URL, not only pathname
> HotRelease/4.3.9: fix analytics collection

- src/common/enums/text.ts
- src/components/Dialogs/TagDialog/Content.tsx
> fix(en-copy): for creating new tags

- src/components/Expandable/index.tsx
https://github.com/thematters/matters-web/issues/2699
> fix height calculation error

- src/views/TagDetail/Articles/index.tsx
https://github.com/thematters/matters-web/issues/2716
> fix:Show the same result when switching tag feeds

- src/views/TagDetail/Articles/index.tsx
https://github.com/thematters/matters-web/issues/2716
> *[master]* hoxfix: show the same result when switching tag feeds

- src/common/utils/route.ts
- src/components/Comment/CreatedAt/index.tsx
- src/components/Expandable/index.tsx
- src/components/Notice/ArticleNotice/ArticleNewAppreciationNotice.tsx
- src/components/Notice/ArticleNotice/CircleNewArticle.tsx
- src/components/Notice/CircleNotice/CircleNewBroadcastComments.tsx
- src/components/Notice/CircleNotice/CircleNewDiscussionComments.tsx
- src/components/Notice/CircleNotice/CircleNewUserNotice.tsx
- src/components/Notice/CommentCommentNotice/CommentNewReplyNotice.tsx
- src/components/Notice/CommentNotice/ArticleNewCommentNotice.tsx
- src/components/Notice/CommentNotice/CircleNewBroadcastNotice.tsx
- src/components/Notice/CommentNotice/CommentMentionedYouNotice.tsx
- src/components/Notice/CommentNotice/SubscribedArticleNewCommentNotice.tsx
- src/components/Notice/NoticeCircleName.tsx
- src/components/Notice/NoticeComment.tsx
- src/components/Notice/NoticeHeadActors.tsx
- src/components/Notice/UserNotice/UserNewFollowerNotice.tsx
- src/components/Tag/index.tsx
- src/views/ArticleDetail/TranslationToast/index.tsx
- src/views/Settings/index.tsx
* support anchor link for circle notice;
* add translations for circle notices;
* fix suffix `0` on tag component;
> feat(notice): support anchor link for circle notice

- src/components/Dialogs/ShareDialog/Content.tsx
- src/components/Dialogs/ShareDialog/styles.css
> fix: revise footer button

- .github/workflows/test.yml
Turn on test when pushing to master/main branch
> fix(test): enable test when push to master/main branch

- src/views/About/Hero/index.tsx
- src/views/About/Intro/index.tsx
- src/views/About/JoinUs/index.tsx
- src/views/About/Stats/index.tsx
- src/views/About/Timeline/index.tsx
> fix: update about us after test

- package.json
> chore(release): v4.5.1

- src/views/Home/Feed/Authors/index.tsx
> hotfix(authors): correct the url of see-all button in mobile view

- src/views/Me/Wallet/Balance/FiatCurrency.tsx
> fix(Wallet): payout condition

- src/components/Forms/PaymentForm/PayTo/Confirm/index.tsx
- src/components/Forms/PaymentForm/PaymentInfo/index.tsx
- src/components/Forms/PaymentForm/PaymentInfo/styles.css
- src/components/Forms/PaymentForm/Processing/index.tsx
> feat(Donation): display address or LikerID in <PaymentInfo>

- src/common/enums/externalLinks.ts
- src/components/Forms/PaymentForm/PayTo/CurrencyChoice/index.tsx
- src/components/Forms/PaymentForm/PayTo/CurrencyChoice/styles.css
- src/components/Forms/PaymentForm/Processing/index.tsx
- src/components/UserDigest/Mini/index.tsx
- src/components/UserDigest/Mini/styles.css
* reuse `<UserDigest.Mini>` in donation dialog;
* revise copy of USDT donation processing;
> Bugfixes and enhancement on donation

- src/common/enums/externalLinks.ts
- src/components/Forms/PaymentForm/PayTo/SetAmount/index.tsx
- src/components/Forms/WalletAuthForm/Select.tsx
- src/components/Forms/WalletAuthForm/styles.css
- src/components/Layout/SideFooter/index.tsx
- src/views/Guide/content.ts
- src/views/Help/index.tsx
- src/views/Settings/Learn/index.tsx
* show tutorial link on wallet login;
* revise guide page;
* revise approval copy;
* revise footer PWA link;
> feat(donation): show tutorial link on wallet login

- src/components/Dialogs/DonationDialog/index.tsx
- src/components/Dialogs/DonatorsDialog/Content.tsx
- src/components/Dialogs/DonatorsDialog/gql.ts
- src/components/Editor/ToggleAccess/SupportSettingDialog/Content.tsx
- src/components/Editor/ToggleAccess/SupportSettingDialog/index.tsx
- src/components/Editor/ToggleAccess/index.tsx
- src/components/Forms/PaymentForm/PayTo/Confirm/index.tsx
- src/components/Forms/PaymentForm/PayTo/SetAmount/index.tsx
- src/components/Forms/PaymentForm/Processing/index.tsx
- src/components/GQL/updates/appreciation.ts
- src/components/GQL/updates/donation.ts
- src/views/ArticleDetail/AppreciationButton/index.tsx
- src/views/ArticleDetail/Collection/index.tsx
- src/views/ArticleDetail/EditMode/Header/index.tsx
- src/views/ArticleDetail/EditMode/index.tsx
- src/views/ArticleDetail/MetaInfo/index.tsx
- src/views/ArticleDetail/SupportWidget/SupportButton/index.tsx
- src/views/ArticleDetail/SupportWidget/index.tsx
- src/views/ArticleDetail/Toolbar/DonationButton/index.tsx
- src/views/ArticleDetail/Toolbar/index.tsx
- src/views/ArticleDetail/gql.ts
- src/views/ArticleDetail/index.tsx
fix(fallback-empty-string): fallback mediaHash/dataHash to '' empty s… related thematters/matters-server#2912
resolves #2882
> fix(use-article-node-id): use articleNodeId to query

- src/components/Dialogs/DonationDialog/index.tsx
- src/components/Dialogs/DonatorsDialog/Content.tsx
- src/components/Dialogs/DonatorsDialog/gql.ts
- src/components/Editor/ToggleAccess/SupportSettingDialog/Content.tsx
- src/components/Editor/ToggleAccess/SupportSettingDialog/index.tsx
- src/components/Editor/ToggleAccess/index.tsx
- src/components/Forms/PaymentForm/PayTo/Confirm/index.tsx
- src/components/Forms/PaymentForm/PayTo/SetAmount/index.tsx
- src/components/Forms/PaymentForm/Processing/index.tsx
- src/components/GQL/updates/appreciation.ts
- src/components/GQL/updates/donation.ts
- src/views/ArticleDetail/AppreciationButton/index.tsx
- src/views/ArticleDetail/Collection/index.tsx
- src/views/ArticleDetail/EditMode/Header/index.tsx
- src/views/ArticleDetail/EditMode/index.tsx
- src/views/ArticleDetail/MetaInfo/index.tsx
- src/views/ArticleDetail/SupportWidget/SupportButton/index.tsx
- src/views/ArticleDetail/SupportWidget/index.tsx
- src/views/ArticleDetail/Toolbar/DonationButton/index.tsx
- src/views/ArticleDetail/Toolbar/index.tsx
- src/views/ArticleDetail/gql.ts
- src/views/ArticleDetail/index.tsx
This reverts commit 938076450840e8d8042b7e75ae340a40fd00230f.
> Revert "fix(use-article-node-id): use articleNodeId to query"

- src/components/ArticleDigest/DropdownActions/RemoveTagButton.tsx
- src/components/ArticleDigest/DropdownActions/SetTagSelectedButton.tsx
- src/components/ArticleDigest/DropdownActions/SetTagUnselectedButton.tsx
- src/components/ArticleDigest/DropdownActions/index.tsx
- src/components/ArticleDigest/Feed/index.tsx
- src/components/Dialogs/TagAdoptionDialog/index.tsx
- src/components/Dialogs/TagEditorDialog/index.tsx
- src/components/Dialogs/TagLeaveDialog/index.tsx
- src/views/TagDetail/Articles/index.tsx
- src/views/TagDetail/index.tsx
https://matters.canny.io/bug-reports/p/f1f985
> fix(tag-detail): fix missing add/remove article to tag buttons

- src/common/enums/text.ts
- src/common/utils/text.ts
- src/components/ArticleDigest/Card/index.tsx
- src/components/Dialogs/DonatorsDialog/Content.tsx
- src/components/GQL/updates/donation.ts
- src/components/UserDigest/Plain/index.tsx
- src/components/UserDigest/Plain/styles.css
- src/views/ArticleDetail/SupportWidget/Donators/gql.ts
- src/views/ArticleDetail/SupportWidget/Donators/index.tsx
- src/views/ArticleDetail/SupportWidget/Donators/styles.css
- src/views/ArticleDetail/SupportWidget/styles.css
- src/views/ArticleDetail/index.tsx
Changes:
- Represent new single supporter UI on SupporterWidget;
- move cc license to end of article;
- Fix SupporterList Dialog copy;
> fix(single-supporter): move cc license to end of article

- package-lock.json
- package.json
- src/components/Forms/SelectAuthMethodForm/index.tsx
- src/components/Forms/WalletAuthForm/Connect.tsx
- src/components/UserProfile/TraveloggersAvatar/LogbookDialog/index.tsx
- src/views/TagDetail/Buttons/AddButton/CreateDraftMenuItem/index.tsx
- src/views/User/Articles/UserArticles.tsx
> fix(dialog): fix dialog spacing

- package-lock.json
- src/components/Dialogs/ENSDialog/Complete.tsx
- src/components/Dialogs/ENSDialog/ConnectWallet.tsx
- src/components/Forms/WalletAuthForm/Select.tsx
> feat(ens): fix typo

- .github/workflows/deploy.yml
- .github/workflows/storybook.yml
- .github/workflows/test_build.yml
- src/components/Root/index.tsx
Reverts thematters/matters-web#3022
> Revert "fix(ci): add step to install apollo for gen:type"

- src/components/Buttons/FollowUser/Follow.tsx
- src/components/Buttons/FollowUser/Unfollow.tsx
- src/components/Buttons/FollowUser/index.tsx
- src/components/UserDigest/Rich/index.tsx
- src/components/UserDigest/Rich/styles.css
- src/components/UserDigest/Verbose/index.tsx
- src/views/Follow/Feed/FollowingRecommendUser/index.tsx
- src/views/Home/Feed/Authors/index.tsx
* add padding-right to <UserDigest.Rich> conditionally
* fix spacing of `<FollowUserButton>`
> fix(user): add padding-right to <UserDigest.Rich> conditionally

- .env.dev
- .github/workflows/deploy.yml
Reverts thematters/matters-web#3071
> Revert "feat(assets): test R2 deployment on production domain"

- src/views/ArticleDetail/SupportWidget/styles.css
https://github.com/thematters/matters-web/issues/3028
https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=7726%3A50188&t=1APcJCN7Alt8yn13-4
> fix(SupportWidget): fix donation records align

- src/components/Dialogs/LikeCoinDialog/SetupLikeCoin/Binding/index.tsx
- src/components/Forms/PaymentForm/ConnectStripeAccount/Onboarding.tsx
- src/components/Forms/PaymentForm/Processing/index.tsx
- src/components/Forms/PaymentForm/SubscribeCircle/Processing/index.tsx
- src/views/ArticleDetail/EditMode/Header/index.tsx
- src/views/ArticleDetail/EditMode/PublishState/PendingState.tsx
- src/views/ArticleDetail/EditMode/PublishState/PublishedState.tsx
- src/views/ArticleDetail/EditMode/PublishState/index.tsx
- src/views/ArticleDetail/index.tsx
- src/views/Me/DraftDetail/PublishState/PendingState.tsx
* fix revised article settings won't redirect to article detail page; 
* fix keep polling even if component is unmounted [0];
[0] https://dev.to/lico/usequery-pollinterval-with-cache-and-network-doesnt-stop-to-make-requests-after-unmounting-a-component-4hp8
> fix(article): revise article settings wont redirect to article page; 

- src/components/CircleDigest/Mini/index.tsx
- src/components/Layout/Header/MeButton/index.tsx
- src/components/Layout/NavBar/NavListItem.tsx
- src/components/Layout/NavBar/index.tsx
- src/components/Notice/NoticeActorAvatar.tsx
- src/components/Spinner/index.tsx
- src/components/TagDigest/Feed/index.tsx
- src/components/TagDigest/Sidebar/index.tsx
- src/components/UserDigest/Rich/index.tsx
- src/components/UserDigest/Verbose/index.tsx
- src/views/About/Hero/index.tsx
- src/views/Follow/Feed/FollowingRecommendUser/index.tsx
- src/views/Home/Announcements/Carousel/Dot.tsx
- src/views/Migration/index.tsx
* links must have discernible text;
> Fix A11Y issues

- src/components/Expandable/styles.css
Use clip instead of hidden in order to be compatible with Safari 15 and below
> [hotfix - develop](Expandable): Compatible with Safari below 15

- package-lock.json
- package.json
- src/common/utils/route.ts
- src/components/Share/Buttons/Douban.tsx
- src/components/Share/Buttons/Email.tsx
- src/components/Share/Buttons/Facebook.tsx
- src/components/Share/Buttons/LINE.tsx
- src/components/Share/Buttons/Telegram.tsx
- src/components/Share/Buttons/Twitter.tsx
- src/components/Share/Buttons/Weibo.tsx
- src/components/Share/Buttons/WhatsApp.tsx
- src/views/OAuth/Authorize/index.tsx
Also, remove `query-string` package
> fix(ssr): use `router.asPath` instead of `window.location.search` on OAuth/Authorize

- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/components/Notice/CircleNotice/CircleNewDiscussionComments.tsx
- src/components/Notice/TagNotice/TagAddEditorNotice.tsx
- src/components/Notice/TagNotice/TagAdoptionNotice.tsx
- src/components/Notice/TagNotice/TagLeaveEditorNotice.tsx
- src/components/Notice/TagNotice/TagLeaveNotice.tsx
- src/views/Home/Feed/Authors/gql.ts
- src/views/Home/Feed/Authors/index.tsx
- src/views/Home/Feed/Tags/index.tsx
- src/views/Home/Sidebar/Authors/gql.ts
- src/views/Home/Sidebar/Authors/index.tsx
- src/views/Home/Sidebar/Tags/index.tsx
Also, enhance random logic based on totalCount
> fix(sidebar): fix skip query & render content if random is 0

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/components/BlockUser/Button/index.tsx
- src/components/Dialogs/RssFeedDialog/Content.tsx
- src/components/Dialogs/ShareDialog/Copy.tsx
- src/components/Layout/Header/ShareButton/index.tsx
- src/components/Share/Buttons/Douban.tsx
- src/components/Share/Buttons/Email.tsx
- src/components/Share/Buttons/Weibo.tsx
- src/components/UserProfile/CircleWidget/index.tsx
- src/components/UserProfile/DropdownActions/index.tsx
- src/components/UserProfile/index.tsx
- src/views/User/Articles/UserArticles.tsx
- src/views/User/UserTabs/index.tsx
Migrate User Page including:
- Share and `...` Dropdown button
- RSS feed modal
- Circle Widget
- Article/Respinse Tab
- Created xxx  articles In total xxx words
> feat(i18n): migrate user page

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/components/ArticleDigest/DropdownActions/SetTagSelectedButton.tsx
- src/views/TagDetail/ArticlesCount/index.tsx
- src/views/TagDetail/DropdownActions/index.tsx
Add plural for article/articles in Tag detail page
> fix(i18n): revise tag detail copies

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/components/ArticleDigest/DropdownActions/RemoveTagButton.tsx
- src/components/Comment/DropdownActions/CollapseComment/Button.tsx
- src/components/Comment/DropdownActions/DeleteComment/Dialog.tsx
- src/components/Forms/CreateCircleForm/Init.tsx
- src/components/Forms/CreateCircleForm/Profile.tsx
- src/components/Search/SearchBar/index.tsx
- src/views/Circle/Analytics/ContentAnalytics/ContentDigest/index.tsx
- src/views/Circle/Analytics/ContentAnalytics/ContentTabs/index.tsx
- src/views/Circle/Analytics/ContentAnalytics/index.tsx
- src/views/Circle/Settings/ManageInvitation/AddButton/index.tsx
- src/views/Circle/Settings/ManageInvitation/AddInvitationDialog/PreSend.tsx
- src/views/Circle/Settings/ManageInvitation/AddInvitationDialog/Search.tsx
- src/views/Circle/Settings/ManageInvitation/AddInvitationDialog/SelectPeriod/index.tsx
- src/views/Circle/Settings/ManageInvitation/Invites/Accepted/index.tsx
- src/views/Circle/Settings/ManageInvitation/Invites/Pending/index.tsx
- src/views/Circle/Settings/ManageInvitation/Invites/index.tsx
- src/views/Circle/Settings/index.tsx
- src/views/TagDetail/ArticlesCount/index.tsx
Migrate 
- Circle edit/analytics page
- Search bar hint
> feat(i18n): migrate circle edit/analytics translation

- src/components/Forms/EmailLoginForm/Buttons.tsx
Reverts thematters/matters-web#3275
> Revert "fix(form): remove tabIndex=-1 from <PasswordResetDialogButton>"

- src/common/enums/test.ts
- src/components/Forms/EditorSearchSelectForm/index.tsx
- tests/common/publishDraft.ts
- tests/helpers/poms/draftDetail.ts
https://github.com/thematters/matters-web/pull/3301
> Feat/revise publish draft and draftDetail e2e testing

- src/common/utils/analytics.ts
- src/components/Analytics/BannerExposureTracker/index.tsx
- src/components/Analytics/index.tsx
- src/views/Home/Announcements/Carousel/index.tsx
> feat(ga-event): add banner_exposure events to Analytics

- .stylelintrc.json
- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/common/styles/variables/typography.css
- src/components/CircleDigest/Plain/styles.css
- src/components/Comment/DonatorLabel/styles.css
- src/components/Comment/PinnedLabel/styles.css
- src/components/Notice/CommentNotice/CommentPinnedNotice.tsx
- src/components/Tag/styles.css
- src/views/Circle/Analytics/ContentAnalytics/ContentDigest/styles.css
- src/views/Follow/Feed/FollowingFeedHead/styles.css
- tests/helpers/poms/articleDetail.ts
* fix translation on CommentPinnedNotice;
* fix text vertical alignments;
* add test for payment password inputs;
> Fix minor bugs

- lang/zh-Hant.json
- src/components/Cover/styles.css
- src/components/Layout/SideNav/index.tsx
* show search & home buttons on tablet;
* fix translation;
* revert cover border radius;
> fix(nav): show search & home buttons on tablet

- src/common/styles/utils/content.article.css
https://github.com/thematters/matters-web/pull/3260
> fix(article): fix nested figures content style

- package-lock.json
- src/components/Editor/Article/styles.css
- src/components/Editor/Sidebar/Box/index.tsx
- src/components/Editor/Sidebar/Box/styles.css
- src/components/Editor/Sidebar/Response/index.tsx
- src/components/Layout/index.tsx
https://matterslab.slack.com/archives/GDD3U7B71/p1682487842478149?thread_ts=1682477571.620569&cid=GDD3U7B71
> fix(editor): make editor full height

- src/common/utils/withApollo.ts
- src/components/Forms/CreateCircleForm/Init.tsx
- src/components/Forms/CreateCircleForm/styles.css
- src/components/Head/index.tsx
- src/components/SearchSelect/SearchingArea/EditorSearchingArea.tsx
- src/stories/components/Notices/mock.ts
- src/views/Community/content.ts
- src/views/Migration/Features/index.tsx
- src/views/TagDetail/Articles/index.tsx
- src/views/TagDetail/index.tsx
- 7bbbfa46a fix(domain-text-links): change remaining .news text to .town
> fix(domain-text-links): change remaining .news text to .town

- src/components/Layout/SideNav/NavListItem.tsx
- src/components/Layout/SideNav/index.tsx
* fix me button becomes unclickable if viewport is changed;
* show active icon in viewer's cirlce page;
> fix(nav): fix me button becomes unclickable if viewport is changed

- package-lock.json
- package.json
https://github.com/thematters/matters-editor/pull/430/files
> feat(editor): disable italic and underline for legacy editor

- src/components/DateTime/index.tsx
- src/components/DateTime/styles.css
- src/components/Notice/NoticeDate.tsx
This reverts commit f20c71a25322db653759c62836508789899b9c01.
> Revert "Revert "fix(NoticeDate): fix date color""

- src/common/styles/variables/typography.css
- src/components/Layout/SideNav/index.tsx
* render nav search button as link;
* add Noto Sans TC/SC to font family;
> fix(nav): render nav search button as link

- package-lock.json
- package.json
- src/views/ArticleDetail/AppreciationButton/styles.module.css
- src/views/ArticleDetail/index.tsx
* fix superlike icon; 
* fix disabled comment bar if sensitive wall is showing
> fix(css): fix superlike icon;

- src/views/About/Intro/index.tsx
- src/views/About/JoinUs/index.tsx
- src/views/About/JoinUs/styles.module.css
- src/views/About/Stats/index.tsx
- src/views/About/Timeline/index.tsx
- src/views/About/index.tsx
https://github.com/thematters/developer-resource/issues/227
> feat(about): revise about page

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/views/Search/AggregateResults/Articles.tsx
- src/views/Search/AggregateResults/gql.ts
- src/views/Search/index.tsx
> feat(search-page-seo): Improve search page's SEO meta headers

- src/components/Editor/Article/extensions/mention/suggestion.ts
- src/components/Editor/Article/index.tsx
- src/components/Editor/Comment/index.tsx
https://matters.canny.io/bug-reports/p/f01f69
> fix(editor): insert mention list to #editor to prevent click to hide dialog

- src/components/Editor/Article/extensions/mention/suggestion.ts
- src/components/Editor/Article/index.tsx
- src/components/Editor/Comment/index.tsx
https://matters.canny.io/bug-reports/p/f01f69
> [hotfix - master] fix(editor): insert mention list to #editor to prevent click to hide dialog

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/components/ArticleDigest/DropdownActions/ArchiveArticle/Dialog.tsx
- src/components/CollectionDigest/DropdownActions/DeleteCollection/Dialog.tsx
- src/components/CollectionDigest/DropdownActions/PinButton.tsx
- src/components/GQL/updates/userArticles.ts
- src/components/Tabs/styles.module.css
- src/views/User/Articles/UserArticles.tsx
- src/views/User/Collections/UserCollections.tsx
- src/views/User/UserTabs/index.tsx
* Fix copies;
* Fix tabs UI;
* Fix unpin collection toast;
> fix(ui): fix copies & styles issue of user page

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/common/enums/keyValue.ts
- src/components/Buttons/Bookmark/Subscribe.tsx
- src/components/Buttons/Bookmark/Unsubscribe.tsx
- src/components/Buttons/CopyButton.tsx
- src/components/Dialog/Handle.tsx
- src/components/Dialog/index.tsx
- src/components/Dialogs/ENSDialog/LinkENS.tsx
- src/components/Dialogs/FingerprintDialog/ArticleSecret.tsx
- src/components/Dialogs/FingerprintDialog/Content.tsx
- src/components/Forms/PaymentForm/PayTo/SetAmount/index.tsx
- src/components/Forms/PaymentForm/PaymentInfo/index.tsx
- src/components/Layout/Header/MeButton/SideDrawerNav/DrawerContent/index.tsx
- src/components/UserProfile/WalletLabel/WalletAddress/index.tsx
- src/views/ArticleDetail/Wall/Visitor/index.tsx
- src/views/Me/Settings/Settings/Wallet/index.tsx
- src/views/User/UserTabs/index.tsx
* fix unresponsive esc key to close dialog;
* remove `optimisticResponse` for bookmark buttons;
* hide collection tab only if article and collection are both 0;
* retire legacy `translate`;
> feat(dialog): fix unresponsive esc key to close dialog

- src/components/Editor/Article/FloatingMenu/styles.module.css
- src/components/Editor/Article/Title/styles.module.css
- src/views/Me/Analytics/EmptyAnalytics/index.tsx
- src/views/Me/Analytics/EmptyAnalytics/styles.module.css
- src/views/Me/Analytics/index.tsx
* Fix `/me/analytics` layout;
* Fix editor spacings;
> fix(layout): fix me/analytics layout; 

- src/components/ArticleDigest/Feed/index.tsx
- src/components/Dialogs/AddArticlesCollectionDialog/SearchingDialogContent.tsx
- src/components/Dialogs/AddArticlesCollectionDialog/SelectDialogContent.tsx
- src/components/Dialogs/AddArticlesCollectionDialog/gql.ts
- src/components/Dialogs/AddArticlesCollectionDialog/index.tsx
- src/components/Dialogs/AddCollectionsArticleDialog/SelectDialogContent.tsx
- src/components/Dialogs/ShareDialog/Copy.tsx
- src/components/Dialogs/ShareDialog/index.tsx
- src/components/Forms/SelectAuthMethodForm/styles.module.css
- src/components/Forms/WalletAuthForm/styles.module.css
- src/components/GQL/updates/userCollectionDetail.ts
- src/components/Share/Buttons/Douban.tsx
- src/components/Share/Buttons/Email.tsx
- src/components/Share/Buttons/Facebook.tsx
- src/components/Share/Buttons/LINE.tsx
- src/components/Share/Buttons/Telegram.tsx
- src/components/Share/Buttons/Twitter.tsx
- src/components/Share/Buttons/Weibo.tsx
- src/components/Share/Buttons/WhatsApp.tsx
- src/components/UserProfile/AsideUserProfile/index.tsx
- src/stories/components/CollectionDigest/Feed.stories.tsx
- src/views/User/CollectionDetail/CollectionArticles/ViewerArticles.tsx
- src/views/User/CollectionDetail/CollectionArticles/gql.ts
- src/views/User/CollectionDetail/CollectionArticles/index.tsx
- src/views/User/CollectionDetail/CollectionProfile/gql.ts
- src/views/User/CollectionDetail/CollectionProfile/index.tsx
- src/views/User/CollectionDetail/gql.ts
- src/views/User/CollectionDetail/index.tsx
* add `utm_source` to share links;
* add `<Head>` to collection detail;
* make component gqls self-explained;
* linkify aside avatars & displayNames;
* revise img width of `<ArticleDigest.Feed>`;
> feat: add utm_source to share links

- src/components/Avatar/index.tsx
- src/views/Me/DraftDetail/SettingsButton/ConfirmPublishDialogContent/index.tsx
- src/views/User/UserProfile/DropdownActions/index.tsx
* hide block user button for anonymous;
* refetch user profile on publication;
* add tooltip to logbook badge;
> fix(user): hide block user button for anonymous; 

- src/components/CollectionDigest/DropdownActions/EditCollection/Dialog/Content.tsx
- src/components/Dialog/Content/styles.module.css
- src/components/Dialogs/EditTagDialog/Content.tsx
- src/components/Editor/SettingsDialog/List/styles.module.css
- src/components/FileUploader/AvatarUploader/index.tsx
- src/components/FileUploader/CoverUploader/index.tsx
- src/components/Forms/CreateCircleForm/Profile.tsx
- src/components/SearchSelect/styles.module.css
- src/stories/components/Uploader/Avatar.stories.tsx
- src/stories/components/Uploader/Cover.stories.tsx
- src/views/User/UserProfile/DropdownActions/EditProfileDialog/Content.tsx
- src/views/User/UserProfile/FollowingDialog/FeedType/styles.module.css
- src/views/User/UserTabs/index.tsx
* set submit button to loading state on avatar/cover uploading;
* fix missing collection tab on viewing non-author page;
> feat(file): set submit button to loading state on avatar/cover uploading

- src/components/Forms/PaymentForm/PayTo/SetAmount/index.tsx
related to https://github.com/thematters/matters-web/pull/3633/
> fix(dialog): fix dialog submit button unable to click on first click

- src/common/styles/utils/content.article.css
- src/common/styles/utils/content.comment.css
* fix extra indent of first line of code [*](https://github.com/thematters/matters-web/issues/3738);
> fix(editor): fix extra indent of first line of code

- src/common/styles/mixins.css
- src/components/ArticleDigest/Sidebar/index.tsx
- src/components/CircleDigest/Plain/styles.module.css
- src/components/Tag/styles.module.css
- src/components/UserDigest/Rich/styles.module.css
- src/views/Me/Settings/Settings/Account/styles.module.css
- src/views/User/CollectionDetail/CollectionProfile/styles.module.css
- src/views/User/UserProfile/index.tsx
- src/views/User/UserProfile/styles.module.css
* fix missing avatar border on profile page;
* fix cover size of `<ArticleDigest.Sidebar>`;
* fix cropped descenders of letters of user digest;
* fix collection profile spacing;
> fix(user): fix missing avatar border on profile page

- src/components/Forms/EmailSignUpForm/Init.tsx
- src/components/GlobalDialogs/UniversalAuthDialog/index.tsx
- src/views/Auth/Universal/index.tsx
https://github.com/thematters/matters-web/pull/3355
> feat(recaptcha): enable recaptcha for sign up

- src/views/Me/Settings/Account/Socials/index.tsx
- src/views/Me/Settings/Notifications/CircleSettings/index.tsx
- src/views/Me/Settings/Notifications/GeneralSettings/Email.tsx
- src/views/Me/Settings/Notifications/GeneralSettings/index.tsx
https://www.figma.com/file/IbbP1A5KbQTZiIfLAB6Sjq/%E8%A8%BB%E5%86%8A%E8%88%87%E7%99%BB%E5%85%A5?type=design&node-id=1993-12535&mode=design&t=REaISSBt3CddRNHw-0
> feat(tableview): revise hotarea

- src/views/Me/Settings/Account/Email/index.tsx
- src/views/Me/Settings/Account/Password/index.tsx
- src/views/Me/Settings/Account/Socials/index.tsx
- src/views/Me/Settings/Account/Wallet/index.tsx
- src/views/Me/Settings/Button.tsx
* add reusable `<SettingsButton>` and revise hover style;
> feat(settings): revise settings buttons

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/components/Dialogs/RemoveSocialLoginDialog/Content.tsx
- src/components/Dialogs/RemoveSocialLoginDialog/gql.ts
- src/components/Dialogs/SetEmailDialog/Content.tsx
- src/components/Dialogs/SetPasswordDialog/Content.tsx
- src/components/Dialogs/SetUserNameDialog/ConfirmStep.tsx
- src/components/Dialogs/SetUserNameDialog/Content.tsx
- src/components/Dialogs/SetUserNameDialog/InputStep.tsx
- src/components/Dialogs/SetUserNameDialog/gql.ts
- src/components/Dialogs/SetUserNameDialog/hook.ts
- src/components/GlobalDialogs/index.tsx
- src/views/Me/Settings/Account/Password/index.tsx
* force userNameEditable user to confirm the username;
* remove unused `refetchQueries` since mutation with additional fields will trigger local update;
> feat(username): force `userNameEditable` user to confirm the username

- src/views/Me/DraftDetail/index.tsx
refs:
- 202309-product#PO-0007
> fix(draft): skip creating a new draft if update with empty value

- .env.prod
- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/common/enums/csp.ts
- src/common/enums/file.ts
- src/common/utils/form/image.tsx
- src/common/utils/form/index.ts
- src/components/Editor/Article/FloatingMenu/UploadImageButton.tsx
- src/components/Editor/SetCover/Uploader.tsx
- src/components/FileUploader/AvatarUploader/index.tsx
- src/components/FileUploader/CoverUploader/index.tsx
*Note:* base branch is `feat/direct-image-upload`
> feat(image): validate image before uploading

- src/components/Forms/EmailLoginForm/index.tsx
- src/components/Forms/EmailSignUpForm/Init.tsx
refs:
- 202309-product#ZN-0032
- https://github.com/thematters/matters-web/pull/3863
> fix(signup): pass langauge to sendVerificationCode mutation

- src/components/Forms/EmailLoginForm/OtherOptions.tsx
- src/components/Forms/EmailLoginForm/index.tsx
refs:
- 202309-product#ZN-0035
> fix(login): disable sendLoginCode button when mutation is loading

- src/components/Editor/SetCover/Uploader.tsx
related:
* https://github.com/thematters/matters-web/pull/3848
* https://github.com/thematters/matters-web/pull/3793
> fix(draft): create new draft if user tries to upload cover

- src/common/styles/components/dialog.css
- src/components/DialogBeta/index.tsx
- src/components/DialogBeta/styles.module.css
- src/components/Forms/SelectAuthMethodForm/index.tsx
- src/components/GlobalDialogs/UniversalAuthDialog/index.tsx
> fix(UniversalAuthDialog): expand auth dialog

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/components/GlobalToasts/EmailVerificationToast/index.tsx
> fix(EmailVerificationToast): revise copy

- src/common/styles/bases/reset.css
- src/views/ArticleDetail/index.tsx
Also, remove monospace as default font for code tags on reset.css
ref: https://github.com/thematters/matters-web/issues/3828
> feat(article): prefer to fetch article detail data by articleId instead of mediaHash

- src/common/utils/analytics.ts
- src/components/Hook/useDirectImageUpload.tsx
resolve #3850
image_upload with delay_msecs
> feat(ga-event): Emit GA event: image upload time

- src/components/DialogBeta/Handle.tsx
- src/components/DialogBeta/index.tsx
- src/components/DialogBeta/styles.module.css
ref:
[ZN-0037](https://paper.dropbox.com/doc/2023-09-2--CBnISzk2uJucjxB1doRrINuhAg-VKFPLgXuZRB4lXqvDnw0N)
> Fix dialogbeta handle clickable on mobile

- public/static/icons/16px/copy.svg
- public/static/icons/16px/external-link.svg
- src/components/Dialogs/FingerprintDialog/ArticleSecret.tsx
- src/components/Dialogs/FingerprintDialog/Content.tsx
- src/components/Dialogs/FingerprintDialog/SectionCard/styles.module.css
- src/components/Dialogs/FingerprintDialog/styles.module.css
- src/components/Dialogs/RssFeedDialog/Content.tsx
* revise `<FingerprintDialog>` styles;
* revise `<IconExternalLink16>` and `<IconCopy16>` icons;
refs:
- 2023-09-produce-02#PL-0012
> feat(dialog): revise FingerprintDialog styles

- src/components/CollectionDigest/DropdownActions/DeleteCollection/Dialog.tsx
- src/views/User/UserTabs/index.tsx
ref:
https://matterslab.slack.com/archives/GDD3U7B71/p1697165036194219?thread_ts=1696943540.038749&cid=GDD3U7B71
> fix(DeleteCollection): fix check empty collection

- src/components/Layout/index.tsx
ref:
202309--product-02#ZN0040
> fix(Layout): remove pull to refresh

- src/components/Hook/useColorThief.tsx
fix theme color of pinnedWork not updated after revision of article cover in Firefox 
ref:
https://feedback.matters.town/bug-reports/p/cover
> fix(useColorThief): fix theme color

- src/components/Layout/index.tsx
This reverts commit 7e9ea2d248884e7f318872b4135afddb190ab18c.
> Revert "fix(Layout): remove pull to refresh"

- src/views/ArticleDetail/index.tsx
https://github.com/thematters/matters-web/pull/3883
> fix(ArticleDetail): refetch article public after revise article

- src/components/Forms/Verification/SendCodeButton/index.tsx
https://github.com/thematters/matters-web/pull/3780
> [hotfix] fix(recaptcha): enable recaptcha for wallet login

- lang/zh-Hant.json
> fix(lang): fix en copy

- src/components/Dialog/Dialog.test.tsx
- src/components/List/List.test.tsx
- src/components/Menu/Menu.test.tsx
- src/components/Popper/Dropdown.test.tsx
- src/components/Popper/Tooltip.test.tsx
- src/components/Popper/index.tsx
- src/components/TableView/TableView.test.tsx
- vitest.setup.ts
Base branch: `feat/unit-test-wrapper`
* Add tests for `<Dialog>`, `<Dropdown>`, `<Menu>`, `<List>`, `<TableView>`;
> Unit Test / Pt.2

- src/views/ArticleDetail/AppreciationButton/index.tsx
- src/views/ArticleDetail/AppreciationButton/styles.module.css
* skip showing the Civic Liker dialog for non-liker;
* fix spacing left on appreciation button [[0]](https://matterslab.slack.com/archives/C04EL0S6ESU/p1697511584085999);
> feat(likecoin): fix appreciation button styles

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/common/enums/file.ts
- src/common/utils/form/image.tsx
- src/common/utils/url.ts
- src/components/ArticleDigest/Feed/index.tsx
- src/components/ArticleDigest/Sidebar/index.tsx
- src/components/Book/index.tsx
- src/components/Cover/index.tsx
- src/components/Editor/Article/FloatingMenu/UploadImageButton.tsx
- src/components/Editor/SetCover/Selector.tsx
- src/components/Editor/SetCover/Uploader.tsx
- src/components/Editor/Sidebar/Cover/index.tsx
- src/components/FileUploader/AvatarUploader/index.tsx
- src/components/FileUploader/CoverUploader/index.tsx
- src/components/ResponsiveImage/index.tsx
- src/components/TagDigest/Feed/index.tsx
- src/components/TagDigest/Sidebar/index.tsx
- src/views/Follow/Feed/FollowingRecommendArticle/index.tsx
resolve https://github.com/thematters/developer-resource/issues/253
> feat(upload): adjust gif support

- src/common/utils/url.ts
- src/components/Editor/Article/BubbleMenu/index.tsx
https://matters.canny.io/bug-reports/p/98efe8
> feat(editor): support linkify URL w/o protocol

- src/common/utils/url.ts
https://github.com/thematters/matters-web/pull/3967/files
> fix(editor): support linkify URL w/o protocol

- src/common/utils/url.ts
https://github.com/thematters/matters-web/pull/3967/files
> [hotfix - master] fix(editor): support linkify URL w/o protocol

- src/common/utils/oauth.ts
related doc: https://developers.google.com/identity/openid-connect/openid-connect#authenticationuriparameters
> feat(oauth): force google login to not skip account chooser

- src/components/Hook/useDirectImageUpload.tsx
throw errors if cloudflare images api returns no success
> fix(image-errors): check directImageUpload response

- src/views/Me/DraftDetail/index.tsx
https://feedback.matters.town/bug-reports/p/c7d8a2
> fix(editor): create draft first if not exists on upload embed image

- src/views/Me/DraftDetail/index.tsx
https://feedback.matters.town/bug-reports/p/c7d8a2
> [hotfix - master] fix(editor): create draft first if not exists on upload embed image

- src/components/ArticleDigest/Feed/index.tsx
- src/components/ResponsiveImage/index.tsx
- src/definitions/images.d.ts
- src/views/Home/Announcements/Carousel/index.tsx
- src/views/Home/Feed/MainFeed/index.tsx
Adjust image loading strategy #3914
> feat(images-fetch): fetchPriority for announcementCover & feed images

- src/components/Dialogs/ShareDialog/Copy.tsx
use current login user's userName as referral code as a default scheme
> feat(referral): append referral code to copy link

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/views/Me/Works/Published/SortTabs.tsx
> fix(MyWorks): revise copy

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/views/User/UserProfile/BadgeNomadDialog/Content.tsx
- src/views/User/UserProfile/BadgeNomadDialog/index.tsx
- src/views/User/UserProfile/BadgeNomadDialog/styles.module.css
Implementation of Digital Nomad program
for thematters/developer-resource#326
> feat(nomad-badges): add spacing to share button mobile

- src/components/ArticleDigest/DropdownActions/ToggleRecommendArticle/Button.tsx
- src/components/ArticleDigest/DropdownActions/ToggleRecommendArticle/Dialog.tsx
- src/views/User/UserProfile/DropdownActions/ToggleRestrictUser/Button.tsx
refs:
- 2023-12-cc-01#YS-001
- 2023-12-cc-01#YS-002
- 2023-12-cc-01#YS-003
> fix(admin): fix copy and UI of admin actions

- src/common/utils/oauth.test.ts
- src/common/utils/oauth.ts
- src/components/Dialogs/ShareDialog/Buttons/Douban.tsx
- src/components/Dialogs/ShareDialog/Buttons/Email.tsx
- src/components/Dialogs/ShareDialog/Buttons/Facebook.tsx
- src/components/Dialogs/ShareDialog/Buttons/LINE.tsx
- src/components/Dialogs/ShareDialog/Buttons/Telegram.tsx
- src/components/Dialogs/ShareDialog/Buttons/Twitter.tsx
- src/components/Dialogs/ShareDialog/Buttons/Weibo.tsx
- src/components/Dialogs/ShareDialog/Buttons/WhatsApp.tsx
- src/components/Forms/EmailLoginForm/index.tsx
- src/components/Forms/WalletAuthForm/Connect.tsx
- src/views/Callback/LoginCallback.tsx
- src/views/Callback/SocialCallback.tsx
problem in `src/common/utils/oauth.ts` converted `undefined` to string `"undefined"`
> fix(strip-undefined): strip undefined value from referralCode

- src/views/About/Footer/index.tsx
will roll back after verification done
> [hot release] feat(copyright): update for Meta business verification

- src/views/About/Footer/index.tsx
Reverts thematters/matters-web#4117
> Revert "[hot release] feat(copyright): update for Meta business verification"

- src/common/utils/oauth.test.ts
- src/common/utils/oauth.ts
- src/components/Hook/useRoute.test.ts
* https://feedback.matters.town/admin/board/bug-reports/p/5ead1f
* https://github.com/thematters/matters-web/pull/4101/files#diff-34044f5cabbd1c8c0a3cb628cc34631b16a46aa0903711314874c4ef5fb16c58
> fix: fix signupCallbackUrl

- src/common/utils/oauth.test.ts
- src/common/utils/oauth.ts
- src/components/Hook/useRoute.test.ts
* https://feedback.matters.town/admin/board/bug-reports/p/5ead1f
* https://github.com/thematters/matters-web/pull/4101/files#diff-34044f5cabbd1c8c0a3cb628cc34631b16a46aa0903711314874c4ef5fb16c58
> [hotfix - master] fix: fix signupCallbackUrl

- .github/workflows/deploy.yml
- .github/workflows/storybook.yml
- .github/workflows/test_build.yml
- .github/workflows/test_e2e.yml
- .github/workflows/test_unit.yml
- package.json
> feat(node-v18): Bump deps: Node.js 18.x (client-side)

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/views/ArticleDetail/Wall/Sensitive/index.tsx
- src/views/ArticleDetail/Wall/Sensitive/styles.module.css
https://github.com/thematters/matters-web/issues/4144
> feat(ArticleDetail): update sensitive wall

- src/views/ArticleDetail/Toolbar/DesktopToolbar/index.tsx
- src/views/ArticleDetail/Toolbar/FloatToolbar/index.tsx
- src/views/ArticleDetail/index.tsx
https://github.com/thematters/developer-resource/issues/336
> feat(ArticleDetail): open drawer logic

- src/components/Dialog/styles.module.css
https://feedback.matters.town/bug-reports/p/0b9b29
prev PR: https://github.com/thematters/matters-web/pull/815
> fix(dialog): remove unused pseudo-element of <Dialog> ".container"

- src/components/Dialog/styles.module.css
- src/components/Interaction/LinkWrapper/index.tsx
- src/components/Interaction/LinkWrapper/styles.module.css
* https://github.com/thematters/matters-web/pull/4182
* https://github.com/thematters/matters-web/pull/4183
> [hotfix] fix comment UI and input dialog issues

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/common/enums/text.ts
- src/components/Dialogs/ENSDialog/LinkENS.tsx
- src/components/Forms/PaymentForm/PayTo/SetAmount/SubmitButton.tsx
- src/components/Forms/PaymentForm/PayTo/SetAmount/index.tsx
- src/components/Forms/PaymentForm/Processing/index.tsx
* prompt to reapprove if exceeded allowance
* skip polling tx state if tx id is not provided
refs:
- 2024-02-product-01#PN-0002
- 2024-02-product-01#PN-0004
https://github.com/thematters/developer-resource/issues/374
> fix(donation): prompt to reapprove if exceeded allowance

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/components/Forms/PaymentForm/PayTo/SetAmount/SetAmountHeader/WhyOptimismDialog/index.tsx
[Discussion](https://matterslab.slack.com/archives/G8877EQMS/p1709705516571839?thread_ts=1708929119.178499&cid=G8877EQMS)
> feat(donation): revise copy of OP intro

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/components/Button/index.tsx
- src/components/Button/styles.module.css
- src/components/Dialogs/DonationDialog/Content.tsx
- src/components/Forms/PaymentForm/PayTo/Confirm/index.tsx
- src/components/Forms/PaymentForm/PayTo/Confirm/styles.module.css
- src/components/Forms/PaymentForm/PaymentInfo/index.tsx
- src/components/Forms/PaymentForm/PaymentInfo/styles.module.css
- src/components/Spinner/index.tsx
- src/components/Spinner/styles.module.css
- src/views/ArticleDetail/Support/SupportAuthor/index.tsx
https://github.com/thematters/developer-resource/issues/389
> feat(ArticleDetail): revise credit confirm step

- src/components/Dialogs/DonationDialog/Content.tsx
- src/components/Forms/PaymentForm/Processing/index.tsx
ref:
2024-02-product-01#PN-0002
> fix(donation): switch to the currencyChoice step when close donation dialog

- src/components/Dialogs/DonationDialog/Content.tsx
- src/components/Forms/PaymentForm/Processing/index.tsx
ref:
2024-02-product-01#PN-0002
> *Master*-HOTFIX(donation): switch to the currencyChoice step when close donation dialog

- package-lock.json
- src/components/Forms/PaymentForm/PayTo/SetAmount/index.tsx
ref:
https://feedback.matters.town/bug-reports/p/likecoin-3
> fix(SetAmount): fix USDT exceeded allowance error

- package-lock.json
- src/components/Forms/PaymentForm/PayTo/SetAmount/index.tsx
ref:
https://feedback.matters.town/bug-reports/p/likecoin-3
> *MASTER*-hotfix(SetAmount): fix USDT exceeded allowance error

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/components/AuthMethodFeed/AuthWalletFeed.tsx
- src/components/AuthMethodFeed/styles.module.css
- src/views/ArticleDetail/Support/SupportAuthor/index.tsx
- src/views/ArticleDetail/Support/SupportAuthor/types.d.ts
https://github.com/thematters/developer-resource/issues/393
> feat(ArticleDetail): add connect wallet step

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/components/Forms/PaymentForm/PayTo/Complete/index.tsx
- src/components/Forms/PaymentForm/PayTo/Confirm/index.tsx
- src/components/Forms/PaymentForm/Processing/index.tsx
https://github.com/thematters/developer-resource/issues/400
> feat(Support): revise like coin support

- src/views/Home/Feed/MainFeed/index.tsx
- src/views/Home/index.tsx
- change the order of sidebar (board -> authors -> tags)
- increase the number of articles from 2 to 5 between sidebar sections on mobile
> feat(sidebar): change the order of sidebar

- src/views/Home/Feed/MainFeed/index.tsx
- change the number of articles from 4 to 5
> feat(sidebar): fix the number of articles between sidebar sections

- package-lock.json
- package.json
- src/components/Head/index.tsx
https://github.com/thematters/matters-web/pull/4207
> refactor(components): migrate Head component from next/head to next-seo

- src/common/utils/route.test.ts
- src/common/utils/route.ts
- src/pages/a/[shortHash].tsx
- src/views/ArticleDetail/gql.ts
- src/views/ArticleDetail/index.tsx
> feat(new-article-path): Revise pathname of article detail page #4196

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/components/BlockUser/Dialog/index.tsx
resolve https://github.com/thematters/developer-resource/issues/379
> feat(copy):  revise copy as blocked users can connect blockers' articles now

- src/components/BlockUser/Button/index.tsx
> fix: fix incorrect icon

- src/components/CommentBeta/DropdownActions/DeleteComment/Dialog.tsx
- src/components/Dialogs/CommentFormBetaDialog/CommentForm/index.tsx
- src/components/Forms/CommentFormBeta/index.tsx
- src/components/GQL/updates/articlePublic.ts
- src/views/ArticleDetail/gql.ts
ref:
2024-05-dev-test#1-ZK-009
> Fix(ArticleDetail): Update commentCount cache after adding a new comment

- src/components/Editor/BottomBar/index.tsx
- src/components/Editor/Sidebar/Collection/index.tsx
- src/components/Editor/index.tsx
- src/components/Forms/EditorSearchSelectForm/index.tsx
- src/components/SearchSelect/SearchingArea/EditorSearchingArea.tsx
- src/views/ArticleDetail/Edit/index.tsx
refs:
- 2024-05-dev-1#RB-011
- https://feedback.matters.town/bug-reports/p/484f04
> fix(article): exclude current editing article on collection search

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/components/Buttons/BackToHome.tsx
- src/components/Context/Language/LanguageContext.tsx
- src/components/Error/index.tsx
- src/pages/[name]/[idOrMediaHash]/index.tsx
refs:
* https://github.com/thematters/developer-resource/issues/373
* https://github.com/thematters/matters-web/issues/4196
* https://github.com/thematters/matters-web/pull/4315
> feat(article): add page to handle legacy article url redirection

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- package-lock.json
- package.json
- src/common/enums/route.ts
- src/common/styles/utils/content.article.css
- src/common/styles/utils/content.comment.css
- src/components/ArticleDigest/DropdownActions/IPFSButton/index.tsx
- src/components/Dialogs/CommentFormBetaDialog/CommentForm/index.tsx
- src/components/Editor/Article/BubbleMenu/index.tsx
- src/components/Editor/Article/styles.module.css
- src/components/Forms/CommentFormBeta/index.tsx
- src/views/ArticleDetail/Edit/Header/index.tsx
- src/views/ArticleDetail/Edit/Header/styles.module.css
- src/views/ArticleDetail/History/InfoHeader/index.tsx
- src/views/ArticleDetail/History/InfoHeader/styles.module.css
- src/views/ArticleDetail/History/Versions/VersionsDropdown/index.tsx
- src/views/ArticleDetail/History/Versions/VersionsSidebar/index.tsx
- src/views/ArticleDetail/History/index.tsx
- src/views/ArticleDetail/MetaInfo/index.tsx
- src/views/ArticleDetail/StickyTopBanner/index.tsx
- src/views/ArticleDetail/StickyTopBanner/styles.module.css
- src/views/ArticleDetail/index.tsx
- src/views/Me/DraftDetail/index.tsx
- src/views/Me/DraftDetail/styles.module.css
refs:
- PR-004
- PR-025
- PR-030
- PR-031
- PR-049
- 2024-05-prod-1#ZN-002
- 2024-05-prod-1#PL-003
- 2024-05-prod-1#PL-006
> Fix editor bugs

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/common/utils/route.ts
- src/components/ArticleDigest/DropdownActions/EditButton.tsx
- src/components/Toast/index.tsx
- src/components/Toast/styles.module.css
- src/stories/mocks/index.ts
- src/views/ArticleDetail/MetaInfo/gql.ts
- src/views/ArticleDetail/MetaInfo/index.tsx
> feat(article): disable edit article entry if exceed revision limit

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/common/utils/form/validate.test.ts
- src/common/utils/form/validate.ts
- src/components/Editor/SetVersionDescription/Content.tsx
- src/components/Editor/ToggleAccess/SupportSettingDialog/Content.tsx
- src/components/Editor/ToggleAccess/SupportSettingDialog/SupportPreview.tsx
> feat(editor): revise error message and validator for for over length

- src/common/styles/utils/content.article.css
- src/components/Layout/index.tsx
- src/views/ArticleDetail/Edit/index.tsx
- src/views/ArticleDetail/History/Versions/VersionsDropdown/index.tsx
- src/views/ArticleDetail/History/Versions/VersionsSidebar/index.tsx
- src/views/Me/DraftDetail/index.tsx
> feat(history): fix sticky position of version sidebar

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/views/ArticleDetail/Edit/Header/index.tsx
> feat(article): remove revision count hint on header

- lang/zh-Hans.json
- lang/zh-Hant.json
- src/views/ArticleDetail/Support/SupportWidget/Donators/index.tsx
> feat: revise copy of anonymous support user

- lang/zh-Hans.json
- lang/zh-Hant.json
- package-lock.json
- package.json
- src/common/styles/components/dialog.css
- src/common/utils/resolvers/clientPreference.ts
- src/common/utils/types/index.ts
- src/components/Balance/index.tsx
- src/components/ClientUpdater/index.tsx
- src/components/Dialog/Content/styles.module.css
- src/components/Dialog/Handle.tsx
- src/components/Dialog/index.tsx
- src/components/Dialogs/CommentFormBetaDialog/index.tsx
- src/components/Editor/Article/BubbleMenu/index.tsx
- src/components/Editor/Article/styles.module.css
- src/components/Form/Select/styles.module.css
- src/components/Forms/EmailLoginForm/index.tsx
- src/components/GQL/queries/clientPreference.ts
- src/views/ArticleDetail/AppreciationButton/AppreciateButton.tsx
- src/views/ArticleDetail/AppreciationButton/index.tsx
- src/views/ArticleDetail/Comments/CommentsDialog/index.tsx
- src/views/Auth/Universal/styles.module.css
* Disable animation for mobile dialogs to fix broke text selection inside dialog;
* Disable scroll lock for comment dialogs;
* Add CSS variable `--vvh` from `window.visualViewport.height` to incorrect `vh` behavior with visual keyboard;
* and make dialog max height to `calc(90 * var(--vvh)`;
* Remove unused home feed auto switcher for new users;
* Fix copies;
refs
* PR-039;
* PR-064;
* PR-058;
* PR-061;
* 2024-05-prod-1#ZN-015
* 2024-05-prod-1#ZN-025
* 2024-05-prod-1#PL-013
> feat(dialog): disable scroll lock for comment dialogs

- src/components/Editor/Article/FloatingMenu/styles.module.css
- src/components/Editor/Article/index.tsx
- src/components/Editor/Article/styles.module.css
- src/components/Layout/index.tsx
- src/components/Layout/styles.module.css
> feat(editor): use --vvh for article editor content height on mobile

- package-lock.json
- package.json
- src/common/utils/text/article.test.ts
- src/common/utils/text/article.ts
- src/components/ArticleDigest/Feed/index.tsx
- src/components/CollectionDigest/Feed/index.tsx
- src/components/CopyToClipboard/index.tsx
- src/components/Dialogs/CommentFormBetaDialog/CommentForm/index.tsx
- src/components/Dialogs/CommentFormDialog/CommentForm/index.tsx
- src/components/Expandable/index.tsx
- src/components/Forms/CommentForm/index.tsx
- src/components/Forms/CommentFormBeta/index.tsx
- src/components/Notice/NoticeContentDigest.tsx
- src/views/ArticleDetail/Edit/Header/index.tsx
- src/views/Follow/Feed/FollowingRecommendArticle/index.tsx
- src/views/Me/DraftDetail/index.tsx
- src/views/Me/History/Comments/index.tsx
> feat: revise `stripHtml` and make plain text as fallback of clipboard content

- package-lock.json
https://github.com/thematters/matters-web/actions/runs/9123486092/job/25085984658
> chore: use npmjs.org as npm registry

- src/views/ArticleDetail/Toolbar/FixedToolbar/index.tsx
- src/views/ArticleDetail/index.tsx
- remove tracker and revert to [previous code](https://github.com/thematters/matters-web/pull/4407/files#diff-e1384fd3453cb6c31ccd3065ac8dbe2a53492749da58e865af7cfe773255bffeL449)
- install tracker in side of the fixed tool bar component
> fix(tracker): remove tracker that cause comment dialog won't open

- src/views/ArticleDetail/Edit/index.tsx
> fix(article): fix unable to upload image && audio on edit article

- .ebextensions/eb-memory-monitor.config
- bin/aws-nextjs-metrics.mjs
the source to be changed to 'develop' branch later;
> feat(memory-metrics): add aws-nextjs-metrics for memory reporting

- src/views/ArticleDetail/MetaInfo/index.tsx
> fix(MetaInfo): show created at time

- src/components/Form/ComposedAmountInput/styles.module.css
ref:
PR-44
https://www.notion.so/matterslab/2024-05-2-5e5d762efde44533ac9e143f87e024b0?p=d2d560cb67cf44cab386ddefb37b2cf3&pm=s
> fix(ComposedAmountInput): fix custom input border color

- src/components/CommentBeta/Feed/styles.module.css
- src/components/Label/styles.module.css
> fix(Feed): fix long display name issue

- src/common/utils/analytics.ts
- src/components/ArticleDigest/DropdownActions/IPFSButton/index.tsx
- src/components/ArticleDigest/DropdownActions/ShareButton.tsx
- src/components/ArticleDigest/DropdownActions/index.tsx
- src/components/Dialogs/SubmitReportDialog/Button.tsx
- src/views/ArticleDetail/AuthorSidebar/Author/index.tsx
- src/views/ArticleDetail/Toolbar/DesktopToolbar/index.tsx
- src/views/ArticleDetail/Toolbar/FixedToolbar/index.tsx
- add trackers for article dropdown button
> feat(tracker): add tracker for article page dropdown button

- src/common/enums/article.ts
- src/components/CommentBeta/Feed/index.tsx
- src/views/ArticleDetail/Comments/CommentDetail/index.tsx
ref:
https://matterslab.slack.com/archives/GA0R09FHN/p1716383082385069
> fix(Comments): update comment feed id name

- src/views/TagDetail/Cover/index.tsx
> feat: update cover page icon size to 20px

- src/views/ArticleDetail/Toolbar/FloatToolbar/index.tsx
- src/views/ArticleDetail/index.tsx
> fix(floating-toolbar): exclude event listener from toolbar

- src/components/Forms/CommentFormBeta/index.tsx
ref:
https://matterslab.slack.com/archives/GDD3U7B71/p1716951130381249?thread_ts=1716947959.451499&cid=GDD3U7B71
> fix(CommentFormBeta): editor blur after clear content

- src/views/ArticleDetail/Toolbar/FloatToolbar/index.tsx
fix [#4370](https://github.com/thematters/matters-web/issues/4370)
> fix(article-details): update to the correct inclusion logic

- src/common/utils/analytics.ts
- src/components/TextSelectionPopover/index.tsx
- src/views/ArticleDetail/Content/index.tsx
ref:
https://matterslab.slack.com/archives/GA0R09FHN/p1717072050897659 https://matterslab.slack.com/archives/CH8BLCMTN/p1717074260052259?thread_ts=1717068906.284559&cid=CH8BLCMTN
> fix(ArticleDetail): fix quote scope error & add data tracker

- src/views/ArticleDetail/AuthorSidebar/Tabs/index.tsx
- src/views/ArticleDetail/AuthorSidebar/index.tsx
ref:
https://github.com/thematters/matters-web/issues/4470
> fix(AuthorSidebar): fix tab error

- src/common/styles/utils/content.comment.css
resolve https://github.com/thematters/matters-editor/issues/478
> fix(comment): revise spacing between blocks

- src/components/Editor/Article/Summary/index.tsx
- src/components/Editor/Article/Title/index.tsx
* trigger height adjustment on paste to textarea
> fix(editor): trigger height adjustment on paste to textarea

- src/views/Me/History/Comments/index.tsx
https://github.com/thematters/matters-server/pull/3747
> fix(history): useQuery instead usePublicQuery to fetch comment history

- src/components/FileUploader/CoverUploader/index.tsx
> fix(CoverUploader): fix empty mask

- package-lock.json
- package.json
- src/common/utils/text/article.test.ts
- src/common/utils/text/article.ts
- src/views/ArticleDetail/Edit/Header/index.tsx
- src/views/Me/DraftDetail/index.tsx
> fix(article): allow figures only content

- package-lock.json
- package.json
ref: https://github.com/thematters/matters-editor/pull/488
resolve: https://github.com/thematters/matters-editor/issues/490
> fix(editor): correct linkify on paste content to editor

- src/components/ProgressBar/index.tsx
- src/views/ArticleDetail/Edit/index.tsx
- src/views/Circle/Analytics/IncomeAnalytics/index.tsx
- src/views/Circle/Analytics/SubscriberAnalytics/index.tsx
- src/views/Home/Announcements/Carousel/index.tsx
- src/views/Me/DraftDetail/index.tsx
- src/views/OAuth/Authorize/index.tsx
- src/views/OAuth/Callback/Failure/index.tsx
- src/views/OAuth/Callback/Success/index.tsx
- src/views/Pay/Callback/Failure/index.tsx
- src/views/Pay/Callback/Success/index.tsx
> refactor(types): properly type some `any`s in the components

- src/common/utils/comment.ts
- src/common/utils/resolvers/clientPreference.ts
- src/common/utils/resolvers/lastFetchRandom.ts
- src/common/utils/url.ts
- src/components/Editor/Article/FloatingMenu/UploadAudioButton.tsx
- src/components/Editor/Article/FloatingMenu/UploadImageButton.tsx
- src/components/Error/index.tsx
- src/components/Form/AmountInput/index.tsx
- src/components/Forms/PaymentForm/ResetPassword/index.tsx
- src/components/Hook/useCarousel.ts
- src/components/Hook/useColorThief.tsx
- src/components/Hook/useNativeEventListener.ts
- src/components/Hook/useOutsideClick.ts
- src/components/Hook/useUnloadConfirm.tsx
- src/components/SearchSelect/StagingArea/DraggableNodes.tsx
- src/components/Slides/index.tsx
- src/components/TableView/Cell/index.tsx
- src/views/Circle/Analytics/FollowerAnalytics/index.tsx
follow up on PR #4578
fix issue #4577
> refactor(types): properly type some remainder `any`s in the component

- src/components/Editor/Article/extensions/mention/MentionList/index.tsx
- src/components/Search/SearchQuickResult/index.tsx
refs:
- 2024-06-prod-2#PR-2406-2-2
> feat(menu): remove outline on focus dropdown items

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/components/Dialogs/EditProfileDialog/Content.tsx
- src/views/User/UserProfile/AsideUserProfile/index.tsx
fix #4606
feel free to merge it once approved, thx
> chore: update copy for updating profile

- src/common/utils/route.ts
- src/components/ArticleDigest/Feed/FooterActions/FooterActions.test.tsx
- src/components/ArticleDigest/Feed/FooterActions/index.tsx
- src/components/ArticleDigest/Feed/index.tsx
- src/views/Home/Feed/IcymiCuratedFeed/index.tsx
- src/views/Home/Feed/MainFeed/index.tsx
fix https://github.com/thematters/matters-web/issues/4607
> refactor(article-digest): remove metadata for featured

- src/components/ArticleDigest/Feed/FooterActions/index.tsx
- src/components/ArticleDigest/Feed/index.tsx
also removes timestamps next to the avatar
re #4607
> fix(footer): css padding is not correctly positioning right

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/common/enums/test.ts
- src/common/utils/text/moment.test.ts
- src/common/utils/text/moment.ts
- src/components/Notice/MomentNotice/Like.tsx
- src/components/Notice/MomentNotice/index.tsx
- src/components/Notice/NoticeDigest/index.tsx
- src/components/Notice/NoticeMomentTitle.tsx
- src/components/Notice/index.tsx
- src/stories/components/Notices/mock.ts
- src/stories/mocks/index.ts
given the size of #4634 , breaking it down into smaller ones. see #4489 for a more detailed outline. [figma](https://www.figma.com/design/0d2OccTXpQVsYtY2fABX4X/%E5%8B%95%E6%85%8B?node-id=2924-18769&t=s9jgRTUPbBFzeVAN-0)
> feat(moment): add notice for liking a moment

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/common/enums/test.ts
- src/common/utils/text/moment.test.ts
- src/common/utils/text/moment.ts
- src/components/Notice/MomentNotice/Mention.tsx
- src/components/Notice/MomentNotice/index.tsx
- src/components/Notice/NoticeDigest/index.tsx
- src/stories/components/Notices/mock.ts
breaking down #4634 , re: #4489
> feat(moment): add notice for mentioned in a moment

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/common/utils/datetime/index.ts
- src/views/CampaignDetail/InfoHeader/Participants/index.tsx
- src/views/CampaignDetail/InfoHeader/Participants/styles.module.css
- src/views/CampaignDetail/InfoHeader/index.tsx
- src/views/CampaignDetail/InfoHeader/styles.module.css
> fix(campaign): show timezone if current is not UTC+8; revise info area line breaks;

- src/common/utils/validator.ts
https://www.notion.so/matterslab/2024-07-2-bad98ba6362c4147840259531e7655be?p=e1445a49831a4e1b8f03bf06479b67e6&pm=s
> fix(validator): remove id

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/common/utils/text/moment.test.ts
- src/components/Notice/CommentNotice/CommentMentionedYouNotice.tsx
- src/components/Notice/MomentNotice/Like.tsx
- src/components/Notice/MomentNotice/Mention.tsx
- src/components/Notice/NoticeMomentTitle.tsx
- src/stories/components/Notices/mock.ts
breaking down #4634 
re: #4489
> feat(moment): add moment comment mentioned

- src/common/utils/analytics.ts
- src/views/ArticleDetail/MetaInfo/index.tsx
- src/views/CampaignDetail/Apply/Button/index.tsx
- src/views/CampaignDetail/ArticleFeeds/MainFeed/index.tsx
- src/views/CampaignDetail/ArticleFeeds/Tabs/index.tsx
- src/views/CampaignDetail/InfoHeader/Participants/Dialog/Content.tsx
- src/views/CampaignDetail/InfoHeader/index.tsx
- src/views/CampaignDetail/SideParticipants/index.tsx
* add event trackers;
* disable apply button if the campaign has not started yet;
> feat(campaign): event trackers

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/common/utils/text/moment.test.ts
- src/components/Notice/CommentNotice/MomentNewCommentNotice.tsx
- src/components/Notice/CommentNotice/index.tsx
- src/components/Notice/NoticeDigest/index.tsx
- src/stories/components/Notices/mock.ts
> feat(moment): commented under a particular moment

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/components/Notice/CommentNotice/CommentMentionedYouNotice.tsx
follow up on https://github.com/thematters/matters-web/pull/4659
[figma](https://www.figma.com/design/0d2OccTXpQVsYtY2fABX4X/%E5%8B%95%E6%85%8B?node-id=2924-19636&t=04nRnbFga8ICjzdk-0)
> fix(moment): missing comment of moment in message

- src/components/Editor/Article/extensions/figureImageUploader/Uploader.tsx
- src/components/Editor/Article/extensions/figureImageUploader/index.ts
> fix(editor): prevent dups upload with same image

- src/views/User/CollectionDetail/index.tsx
> fix(CollectionDetail): like collection error

- src/components/Editor/Article/index.tsx
> fix(editor): fix FigureImageUploader placeholder

- src/components/Forms/PaymentForm/Processing/index.tsx
- src/components/GQL/mutations/payTo.ts
resolve: https://github.com/thematters/matters-server/issues/3859
> feat(donation): make draft tx before sending on-chain tx

- lang/default.json
- lang/en.json
- lang/zh-Hans.json
- lang/zh-Hant.json
- src/components/Comment/DropdownActions/index.tsx
- src/components/Dialogs/MomentDetailDialog/Comments.tsx
- src/components/Dialogs/MomentDetailDialog/Content.tsx
- src/components/Forms/MomentCommentForm/index.tsx
- src/components/Forms/MomentForm/index.tsx
- src/views/User/MomentForm/index.tsx
ref:
PR-2408-2-21
PR-2408-2-46
PR-2408-2-47
PR-2408-2-48
PR-2408-2-49
> Adjust moment comment

- src/components/Dialogs/ArticleCommentFormDialog/CommentForm/index.tsx
- src/components/Dialogs/CircleCommentFormDialog/CommentForm/index.tsx
- src/components/Editor/Article/extensions/customShortcuts/index.ts
- src/components/Editor/Article/extensions/index.ts
- src/components/Editor/Comment/index.tsx
- src/components/Forms/ArticleCommentForm/index.tsx
- src/components/Forms/CircleCommentForm/index.tsx
- src/components/Forms/MomentCommentForm/index.tsx
> feat(editor): support mod+enter to submit comment/moment

- src/components/Dialog/Inner/index.tsx
> feat(Dialog): add composition event listeners

- src/components/Editor/Moment/index.tsx
- src/components/Forms/MomentForm/index.tsx
- src/views/MomentDetail/Edit/index.tsx
resolve: https://github.com/thematters/matters-web/pull/4748
> feat(editor): support mod+enter to submit moment

- src/common/enums/events.ts
- src/components/Dialog/index.tsx
- src/components/Editor/Article/extensions/mention/suggestion.ts
> fix(dialog): bypass dialog focus lock when showing the mention popup on editor

- src/common/utils/url.test.ts
- src/common/utils/url.ts
- src/components/ArticleDigest/AuthorSidebar/index.tsx
- src/components/ArticleDigest/Curated/index.tsx
- src/components/ArticleDigest/Feed/index.tsx
- src/components/ArticleDigest/Sidebar/index.tsx
- src/components/Avatar/index.tsx
- src/components/Book/Article/index.tsx
- src/components/Book/Collection/index.tsx
- src/components/Book/Flat/index.tsx
- src/components/CircleAvatar/index.tsx
- src/components/Editor/ListItem/index.tsx
- src/components/Editor/SetCover/Selector.tsx
- src/components/Editor/Sidebar/Cover/index.tsx
- src/components/MomentDigest/Assets/index.tsx
- src/components/ResponsiveImage/index.tsx
- src/components/TagDigest/Feed/index.tsx
- src/components/TagDigest/Sidebar/index.tsx
- src/views/Follow/Feed/FollowingRecommendArticle/index.tsx
> feat(image): disable image animation except for the avatars

- src/components/Dialogs/ArticleCommentFormDialog/CommentForm/index.tsx
- src/components/Dialogs/CircleCommentFormDialog/CommentForm/index.tsx
- src/components/Forms/ArticleCommentForm/index.tsx
- src/components/Forms/CircleCommentForm/index.tsx
- src/components/Forms/MomentCommentForm/index.tsx
- src/components/Forms/MomentForm/index.tsx
- src/views/MomentDetail/Edit/index.tsx
> fix(form): skip form submission if invalid on mod+enter

- src/components/Comment/Content/Collapsed.tsx
- src/components/Comment/Content/index.tsx
> feat(comment): always open new tab for links on comment content

- src/components/Dialogs/MomentDetailDialog/Content.tsx
related issue https://github.com/thematters/matters-web/pull/4756
> fix(moment): add missing capturClick handler on moment detail dialog

- src/views/CampaignDetail/ArticleFeeds/Tabs/styles.module.css
> fix(CampaignDetail): update tab spacing

- src/components/Dialogs/MomentDetailDialog/styles.module.css
> fix(moment): use vh instead ivh for moment container

- src/components/ArticleDigest/Published/FooterActions/styles.module.css
- src/components/ArticleDigest/Published/index.tsx
> feat(me): revise ArticleDigest.Published styles

- src/components/Button/index.tsx
- src/components/Button/styles.module.css
- src/components/MomentDigest/DropdownActions/index.tsx
> fix(moment): revise moment action button color

- src/common/styles/utils/content.moment.css
- src/components/Editor/Article/index.tsx
> fix(moment): make <br> behaves like <p>

- src/common/styles/utils/content.moment.css
- src/components/Editor/Article/extensions/customShortcuts/index.ts
- src/components/Editor/Moment/index.tsx
> feat(moment): create new paragraph with shift+enter

- public/ads.txt
Adding ads.txt for testing out ad network in Billboard.
Ref: https://support.google.com/adsense/answer/12171612
> Add ads.txt

- src/views/Home/Feed/MainFeed/index.tsx
> fix(Home): fix placeholder

- src/common/styles/bases/defaults.css
- src/components/Layout/SideChannelNav/styles.module.css
> fix(styles): update word-break property for better text handling in defaults.css and remove redundant styles in SideChannelNav

- src/components/Tabs/styles.module.css
- src/views/CampaignDetail/ArticleFeeds/Tabs/styles.module.css
> fix(tabs): apply pixel offset only for desktop since it will cause incorrect scroll bar on mobile
