package-lock.json, package.json, src/common/utils/withApollo.ts
As title.
Also added `node-fetch` to devDependencies, since it's used in `bin/buildFragmentTypes.js`.
=> fix(auth token): retrieve and use auth token from localStorage only during static build

src/common/enums/events.ts, src/common/utils/resolvers/clientPreference.ts, src/components/ClientUpdater/index.tsx, src/components/GlobalDialogs/TermAlertDialog/index.tsx, src/components/Layout/NavMenu/Bottom.tsx, src/components/Root/index.tsx
* Remove clear state on logout since it's stored separately
* Fix `setPrivateFetched`
=> fix(onboarding-tasks): store init state separately based on viewer id

src/components/Buttons/Write/index.tsx, src/components/Comment/FooterActions/index.tsx, src/components/GlobalDialogs/index.tsx, src/components/OnboardingTasks/Tasks/index.tsx, src/views/ArticleDetail/AppreciationButton/SetupLikerIdAppreciateButton.tsx, src/views/ArticleDetail/Donation/index.tsx, src/views/ArticleDetail/Toolbar/CommentBar/index.tsx, src/views/Me/DraftDetail/PublishButton/index.tsx, src/views/Me/Settings/Settings/Wallet/index.tsx, src/views/TagDetail/Buttons/AddButton/CreateDraftMenuItem/index.tsx
This issue was caused by `viewer.likerId`'s changing, which will trigger UI update and make dialog auto closes.
=> Fix <LikeCoinDialog> auto closed on Liker ID finish setup

src/components/Form/index.tsx
Fixed an issue reported by [this article](https://matters.news/@AmateurPagan/%E9%97%B2%E8%AF%9D-matters%E4%B8%80%E4%B8%AA%E5%8F%AF%E8%83%BD%E4%BD%BF%E5%AF%86%E7%A0%81%E6%B3%84%E9%9C%B2%E7%9A%84bug-bafyreibg36s5qsffq6vyj4tphz5vio2ibdmntpebfakpoxwruhec4c6er4) though only happens on JavaScript disabled browser.
=> fix(form): add `method="POST"` to <form>

src/components/Editor/SetCoverDialog/Uploader.tsx, src/components/GQL/updates/draftAssets.ts
Since file upload won't purge cache of draft, updating local cache of draft's assets.
=> fix(asset): local update draft assets if uploaded completely instead of refetch

src/common/enums/csp.ts
should fix large part of #2254  as @robertu7 mentioned there were still others servers when users were copying pictures
these old articles were referencing from `srcSet=https://matters-server-production.s3-ap-southeast-1.amazonaws.com/embed/...` directly
=> update Content-Security-Policy: add matters s3 url

.github/workflows/deploy.yml, .github/workflows/storybook.yml, .github/workflows/test.yml
> The minimum Node.js version has been bumped from 12.0.0 to 12.22.0, which is the first version of Node.js with native ES modules support.
>
> https://nextjs.org/blog/next-12
=> chore(deps): update node version to 12.22

src/components/Term/index.tsx
the 'en' terms & privacy are always shown.
resolves #2376
TOS shows duplicate of terms and privacy policy, under English environment
=> fix/duplicate-tos: show the translations only when lang is not 'en'

src/views/TagDetail/Community/Maintainers/index.tsx
Fix this bug https://github.com/thematters/matters-web/issues/2498.
With this change, now the button look consistent.
=> Make the size of manage button adaptive

src/common/utils/route.ts, src/components/Share/Buttons/Douban.tsx, src/components/Share/Buttons/Email.tsx, src/components/Share/Buttons/Facebook.tsx, src/components/Share/Buttons/LINE.tsx, src/components/Share/Buttons/Telegram.tsx, src/components/Share/Buttons/Twitter.tsx, src/components/Share/Buttons/Weibo.tsx, src/components/Share/Buttons/WhatsApp.tsx, src/views/OAuth/Authorize/index.tsx
all use web builtin APIs (URL / URLSearchParams) instead
=> remove/querystring: npm uninstall querystring

src/common/utils/resolvers/gatewayUrls.ts
Recently Meson has released the new version, we can upgrade to new gateway.
The new gateway format for matters with `https://ipfs.io` as the origin: `https://pz-matters.meson.network`
e.g. 
Filehash + Path:
`https://pz-matters.meson.network/ipfs/bafybeie25thw7ikrtp7umu6x5eyiyijdgqk6zinyolih422q3muytkhn4i/Meson-Network-v1.6.pdf`
->
In my machine:
`https://spec00-bdjkbgckckcbixx-07-matters.mesontracking.com/ipfs/bafybeie25thw7ikrtp7umu6x5eyiyijdgqk6zinyolih422q3muytkhn4i/Meson-Network-v1.6.pdf_m_access_key_wipyboquwr`
=> Upgrade Meson Gateway

src/components/ResponsiveImage/index.tsx
related issues:
* #2630 
* #2620
=> feat(image): force `<ResponsiveImage>` to use `.gif` instead of `.webp` for GIFs

src/common/utils/analytics.ts, src/components/Analytics/CardExposureTracker/index.tsx, src/components/Analytics/TagExposureTracker/index.tsx
for both CardExposure and TagExposure
=> feat(track-exp): add delay_msecs to track delays of exposure events

package.json, src/common/utils/resolvers/gatewayUrls.ts, src/components/Head/index.tsx, src/views/TagDetail/RelatedTags/index.tsx
* dbc561967 (HEAD) feat(web-next): turn noindex to bots for web-next
* 4393e5eda (origin/release/4.3.8, local) Update Meson gateway with new API
* 9690210cc (origin/release/relate-tags-) fix(relate-tags): send with trackRelatedTags instead
- fix with the function call, from previous problem was a meta function not calling
- and, avoid the confusing onClick meta function naming
=> fix(relate-tags): send with trackRelatedTags instead

src/views/TagDetail/RelatedTags/gql.ts, src/views/TagDetail/RelatedTags/index.tsx
- Add Shuffle button component
- Add `random` input in `TagDetailRecommended` query
=> feat(related-tags): add shuffle button and function into related tags

.github/workflows/deploy.yml, .github/workflows/storybook.yml, .github/workflows/test_build.yml, .github/workflows/test_e2e.yml
> The action follows [actions/cache](https://github.com/actions/cache/blob/main/examples.md#node---npm) guidelines, and caches global cache on the machine instead of node_modules, so cache can be reused between different Node.js versions.
>
> https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
=> use global npm cache instead of node_modules cache

src/components/Head/index.tsx, src/pages/_document.tsx
fix #3043 of 58845f214c0, move next/script out of next/head;
see https://stackoverflow.com/a/68059559 
> `next/script` should not be wrapped in `next/head`
but not documented from official https://nextjs.org/docs/basic-features/script
=> feat(adsense-script): adsense NextScript

.env.dev, .github/workflows/deploy.yml
> The only folder you need to host on your CDN is the contents of .next/static/, which should be uploaded as _next/static/ as the above URL request indicates. Do not upload the rest of your .next/ folder, as you should not expose your server code and other configuration to the public.
> https://nextjs.org/docs/api-reference/next.config.js/cdn-support-with-asset-prefix
=> feat(ci): upload only .next/static to R2

src/components/Head/index.tsx
for SEO bots be able to get from:
- https://matters.town/?type=newest
- https://matters.town/?type=icymi
=> fix(canonical-url): only set canonical-url when get path from props

next.config.js, src/common/enums/lang.ts, src/common/utils/language.ts, src/components/Context/Language/LanguageContext.tsx, src/components/Dialogs/ShareDialog/Content.tsx, src/components/Forms/PaymentForm/AddCredit/index.tsx, src/components/Forms/PaymentForm/SubscribeCircle/CardPayment.tsx, src/components/Head/index.tsx, src/components/Hook/useRoute.ts, src/pages/_document.tsx, src/views/ArticleDetail/Toolbar/index.tsx, src/views/ArticleDetail/index.tsx
* remove next.js i18n config (since it's not support [hiding locale prefix](https://github.com/vercel/next.js/discussions/35497)) and use `?locale` for article translation instead;
* also changed href of `<link rel="alternate">` from `/{locale}` to [`?locale`](https://github.com/thematters/matters-web/pull/3561/files#diff-9dfc2532305642f988357bc2494e14b80575e0a2992ddbe19d0fa31fda1d2c71R64-R67); 
* fix <html lang> by [reverting changes of `_document.tsx`](https://github.com/thematters/matters-web/pull/2734);
=> fix(i18n): fix <html lang>

src/common/utils/wallet.ts, src/components/Forms/WalletAuthForm/Select.tsx
This is a follow-up PR of https://github.com/thematters/matters-web/pull/3494
ref:
https://matters.canny.io/bug-reports/p/walletconnect-v10-has-been-sunset
=> feat(wallet): enable walletconnect 2

lang/default.json, lang/en.json, lang/zh-Hans.json, lang/zh-Hant.json, src/views/Search/AggregateResults/Articles.tsx
resolves thematters/matters-server#3536
=> fix(search): Search result remove count

src/components/Forms/EmailLoginForm/index.tsx, src/components/Forms/WalletAuthForm/Connect.tsx, src/views/Callback/LoginCallback.tsx, src/views/Callback/SocialCallback.tsx
refs:
- 202309-product#ZN-0032
- https://github.com/thematters/matters-server/pull/3631
=> fix(signup): pass langauge to sign up mutations

package-lock.json, package.json, src/components/Head/index.tsx
referencing github issue #3838 and recommendation from next-seo docs that next-seo is better suited for this sort of things over next/head. most of the things here overlaps with app router's [metadata API](https://nextjs.org/docs/app/building-your-application/optimizing/metadata) too.
fix #3838
=> refactor(components): migrate Head component from next/head to next-seo

src/components/Head/index.tsx
next-seo provides a nice static json config for seo tags, but for the previous conditionaly rendered dyanmic tags is not too friendly. resorting back to next/head
close #3838
=> refactor(component): revert changes for conditional meta tag renders

src/components/Dialogs/SetUserNameDialog/InputStep.tsx
In the previous state, pasting Matters ID during registration was disabled to alert user the importance of this UUID. However, this presents UX drawbacks to users for unexpected behavior. Reverting to default behavior.
re #4251
=> feat(inputstep): enable paste in matters id input

src/components/Buttons/Write/index.tsx, src/components/Dialog/Content/styles.module.css, src/components/Editor/Article/styles.module.css, src/components/Form/Select/styles.module.css, src/components/Layout/styles.module.css, src/views/Auth/Universal/styles.module.css, src/views/Callback/styles.module.css
* For normal use cases: dvh > ivh > vh;
* For use cases want to exclude the visual keyboard: vvh > dvh > ivh > vh;
refs:
- 2024-05-prod-2#PR-59
=> fix: use dvh as top priority instead of ivh

src/common/enums/keyValue.ts, src/views/ArticleDetail/index.tsx
Since the presence of a floating toolbar, the normal scroll height for page up/down (fn + up/down key on OSX) hides some pixels. Now it will offset the height by the height of the toolbar
close: #4370
=> fix(article-detail): adjust page up/down scroll height for floating toolbar

lang/default.json, lang/en.json, lang/zh-Hans.json, lang/zh-Hant.json, src/components/Notice/NoticeActorName.tsx, src/components/Notice/NoticeComment.tsx, src/views/ArticleDetail/Edit/PublishState/PublishedState.tsx
=> chore(notice-comment): fix various copy issues

src/components/CollectionDigest/DropdownActions/EditCollection/Dialog/Content.tsx, src/components/Dialog/Inner/index.tsx, src/components/Dialogs/AddCollectionDialog/index.tsx, src/components/Dialogs/EditProfileDialog/Content.tsx, src/components/Dialogs/EditTagDialog/Content.tsx, src/components/Dialogs/EditorSearchSelectDialog/index.tsx, src/components/Dialogs/SetUserNameDialog/index.tsx, src/components/Editor/BottomBar/index.tsx, src/components/Editor/SetCover/Dialog.tsx, src/components/Editor/SetVersionDescription/index.tsx, src/components/Editor/SettingsDialog/index.tsx, src/components/Editor/Sidebar/Collection/index.tsx, src/components/Editor/Sidebar/Tags/index.tsx, src/components/Editor/ToggleAccess/SupportSettingDialog/Content.tsx, src/components/Editor/ToggleAccess/SupportSettingDialog/index.tsx, src/components/FileUploader/AvatarUploader/index.tsx, src/components/FileUploader/CoverUploader/index.tsx, src/components/Forms/CreateCircleForm/Profile.tsx, src/stories/components/Uploader/Cover.stories.tsx, src/views/User/UserProfile/BadgesDialog/index.tsx
* make close dialog on click outside as default and disable it for some;
* use session storage to cache form data:
* `<EditProfileDialog>` in user profile;
* `<SupportSettingDialog>` in draft detail;
* `<EditCollection>` dialog in collection detail;
* revise `<AvatarUploader>` and `<CoverUploader>` to return `path` on image uploaded;
Base branch: `feat/form-draft`
=> feat(dialog): make close dialog on click outside as default

lang/default.json, lang/en.json, lang/zh-Hans.json, lang/zh-Hant.json, src/views/Me/Settings/Notifications/GeneralSettings/index.tsx
resolve https://github.com/thematters/matters-server/issues/3950
=> feat(notice): remove `articleCommentPinned` setting

lang/zh-Hans.json, lang/zh-Hant.json, src/views/CampaignDetail/InfoHeader/Participants/Dialog/Content.tsx
* private fetch campaign participant list;
* minor copy update;
refs
- CC-2407-2-2
- CC-2407-2-3
- CC-2407-2-5
- CC-2407-2-7
=> Fix campaign fetching

src/components/ArticleComment/FooterActions/index.tsx, src/components/Dialogs/RssFeedDialog/Content.tsx, src/components/Dialogs/SetPasswordDialog/Content.tsx, src/components/Dialogs/TagEditorDialog/List/index.tsx, src/components/Editor/ToggleAccess/SupportSettingDialog/SupportPreview.tsx, src/components/Forms/PaymentForm/AddCredit/index.tsx, src/components/Forms/PaymentForm/ConnectStripeAccount/Request.tsx, src/components/Forms/PaymentForm/PayTo/Confirm/index.tsx, src/components/Forms/PaymentForm/PayTo/SetAmount/index.tsx, src/components/Forms/PaymentForm/Processing/index.tsx, src/components/Forms/PaymentForm/StripeCheckout/index.tsx, src/components/Spacer/index.tsx, src/components/Spacer/styles.module.css, src/views/ArticleDetail/Collection/index.tsx, src/views/ArticleDetail/Comments/CommentsDialog/ListContent.tsx, src/views/ArticleDetail/Comments/LatestComments/index.tsx, src/views/ArticleDetail/Placeholder/index.tsx, src/views/ArticleDetail/Support/SupportAuthor/index.tsx, src/views/ArticleDetail/Support/SupportWidget/index.tsx, src/views/ArticleDetail/index.tsx, src/views/CampaignDetail/Description/index.tsx, src/views/Follow/index.tsx, src/views/Me/Notifications/index.tsx, src/views/Me/Settings/Misc/index.tsx, src/views/Me/Settings/Notifications/CircleSettings/index.tsx, src/views/Me/Settings/Notifications/index.tsx, src/views/User/UserProfile/DropdownActions/ArchiveUser/Dialog.tsx, src/views/User/UserProfile/FollowingDialog/Content/index.tsx
Also, revise `<Spacer>` prop `size` to use `sp` convention
=> fix(campaign): add spacing to the bottom of campaign detail page

src/components/Editor/Article/extensions/figureImageUploader/Uploader.tsx, src/components/Editor/Article/extensions/figureImageUploader/styles.module.css, src/components/Editor/Article/styles.module.css
* correct cursor position after image uploaded
* add `<figcaption>` placeholder to prevent UI relayout after image uploaded
* remove unused;
ref:
- PR-2408-1-23
=> fix(editor): correct cursor position after image uploaded
